skillrecordings/products

pnpm-workspace.yaml

- PNPM allows double-star directive globs (e.g. `directoyr/**`) in `pnpm-workspaces.yaml`. However,  PNPM avoids `node_modules` (and perhaps anything in gitignore?) from these glob results....magically. At the moment, `turbo` doesn't do this. Double star glob in `turbo` really means "recursive" and not "recursive except for `node_modules`". Switching to single star fixes this to "any package.json one-level down from `./apps/*` and `/packages/*`" which is what you want. 
- Lodash core's `package.json` keywords is a string with commas, which I did not know was allowed. This has no impact other than `turbo`'s go struct for package.json and json marshal code needs to be updated to allow this in the future. 
- I am going to add an official PNPM starter so that there is just less for folks to …

Switch to single-star workspace globs

---

packages/commerce/src/hooks/use-commerce-machine.tsx
packages/commerce/src/machines/commerce/utils.ts

this enables passing `stripePriceId` to commerce machine like so:
```
const [state, send] = useCommerceMachine({
stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID,
})
```

commerce: enable passing price id

---

apps/compilersforhumans/src/layouts/index.tsx

Adds Google Verification meta tag to the Next SEO component for domain email creation per [Google's Directions](https://support.google.com/webmasters/answer/9008080?hl=en#zippy=%2Chtml-tag) from [this question in the Next.js repo](https://github.com/vercel/next.js/discussions/14806).

Add C4H google-verification meta tag

---

packages/player/src/components/controls/side-panel-toggle-control.tsx
packages/player/src/components/player.tsx
packages/player/src/components/shortcut.tsx
packages/player/src/hooks/use-auto-hide-controls.ts
packages/player/src/hooks/use-fullscreen-controls.ts
packages/player/src/styles/scss/layout.scss
packages/player/src/styles/scss/miscellaneous.scss

hides controls in fullscreen when user is inactive for 1250ms.

player: auto hide controls in fullscreen

---

apps/typescriptcourse/src/components/layout.tsx
packages/player/package.json
packages/react/src/components/navigation.test.tsx
packages/react/src/components/navigation.tsx
packages/react/src/layouts/index.tsx

simple change to give Navigation a slot in the Layout component so it can be overridden (or hidden) in this case.

feat(react): Navigation component in layout now has a 'slot'

---

packages/player/package.json
packages/player/src/components/player.tsx

Allows passing `poster="image_url"` to the `<Player>` element.

feat(player): video poster image support

---

packages/player/package.json
packages/player/src/components/controls/volume-menu-button-control.tsx
packages/player/src/components/volume-control/volume-bar.tsx
packages/player/src/styles/scss/components/slider.scss
packages/player/src/styles/scss/components/volume.scss
packages/player/src/styles/scss/miscellaneous.scss
pnpm-lock.yaml

this PR fixes following issues:
https://user-images.githubusercontent.com/25487857/159444562-b42449aa-4445-419a-af81-56d2c1fe2145.mp4

feat(player): improved volume controls a11y

---

apps/next-product-starter/src/styles/globals.css
packages/player/src/components/cue-bar.tsx
packages/player/src/components/cue-form.tsx
packages/player/src/components/seek-bar/index.tsx
packages/player/src/components/volume-control/volume-bar.tsx
packages/player/src/styles/scss/components/cue-form.scss
packages/player/src/styles/scss/variables.scss

update(player): cue bar a11y improvements

---

apps/testingaccessibility/README.md
apps/testingaccessibility/src/components/portable-text/index.tsx
apps/testingaccessibility/studio/schemas/objects/body.js

This adds new Emoji mark so that we can provide `aria-label` for emojis. I've noticed that even though I made the label required in schema, the editor won't highlight it in case it's missing. Might be worth reporting to Sanity team. :) In case the label isn't provided, we hide the emoji for screen readers using `aria-hidden="true"`.
I also added way to link to internal documents, but haven't implemented a react component for it yet.
https://user-images.githubusercontent.com/25487857/164165058-cfefa8cd-bd32-4bda-a01e-d53b18a98e1c.mp4

feat(testingaccessibility): accessible emojis from portable text

---

apps/testingaccessibility/src/components/portable-text/index.tsx
apps/testingaccessibility/src/templates/lesson-template.tsx
packages/player/src/components/controls/fullscreen-toggle-control.tsx
packages/player/src/components/player.tsx
packages/player/src/components/shortcut.tsx
packages/player/src/selectors/index.ts
packages/player/src/styles/scss/components/control-bar.scss

using `<Player enableGlobalShortcuts={false} ...` will switch shortcut events listener from `document` to player's `rootEl`. useful when there are multiple players on a single page. without this, using shortcuts would affect every player instance on page at the same time.

feat(player): ability to disable global shortcuts

---

apps/testingaccessibility/src/templates/article-template.tsx

- change ring focus indicator color to white for elements on green background
to debug `focus-visible` state properly with devtools, add `focus-visible` class and `data-focus-visible-added` property on an element. example:  `<a className="focus-visible" data-focus-visible-added>` (cc @marcysutton)
https://user-images.githubusercontent.com/25487857/173558593-18ce909d-0340-493d-94ee-c4d257d65acb.mp4

update(testingaccessibility): visual focus indicator on article template

---

apps/testingaccessibility/src/components/portable-text/index.tsx

I used these languages in code blocks and it is required that they are registered with Refractor

feat: register css and jsx with Refractor

---

apps/testingaccessibility/prisma/schema.prisma
apps/testingaccessibility/src/lib/purchases.ts
apps/testingaccessibility/src/pages/api/stripe/webhook.ts

this doesn't limit access based on these events but does annotate the purchase so that we will be able to do so easily.

feat(testingaccessibility): adds a status column to purchases

---

apps/testingaccessibility/src/pages/api/stripe/checkout.ts

This fixes following error on checkout reported by a user which I was able to confirm.
```json
{"error":true,"message":"The `expires_at` timestamp must be at least 60 minutes from Checkout Session creation."}
```
from docs: 
`expires_at` The Epoch time in seconds at which the Checkout Session will expire. It can be anywhere from 1 to 24 hours after Checkout Session creation. **By default, this value is 24 hours from creation.**
--- 
We might not need to overwrite this since the default already is 24 hours from session creation?

fix(testingaccessibility): checkout `expires_at`

---

apps/testingaccessibility/src/components/portable-text/index.tsx
apps/testingaccessibility/src/pages/api/srt/[videoResourceId].ts
apps/testingaccessibility/studio/schemas/documents/videoResource.js

https://testingaccessibility.sanity.studio/desk/videoResources;1ae99cd3-c636-4355-9095-b9f31b51ef51
I only affected this one video resource.
It's for this lesson -> http://localhost:3013/learn/semantics-and-aria/build-page-structure-through-headings-and-semantic-landmark-elements/a-note-about-the-header-landmark-solution
For the VideoResource I think using this type of "backlink" has a lot of potential https://www.sanity.io/schemas/list-referring-documents-backlinks-in-sanity-1a8ada64

feat: load srt from sanity

---

apps/protailwind/src/pages/answer.tsx

Had the wrong answer specified. Now it's the right one.

fix(protailwind): the wrong answer was specified as the correct one

---

apps/testingaccessibility/src/components/portable-text/index.tsx

It seems that the only thing to fix it was add the `not-prose` class to `video` portable-text component. 
before:
after:

feat(ta): fix videoplayer frame

---

apps/testingaccessibility/src/components/portable-text/index.tsx
apps/testingaccessibility/src/templates/article-template.tsx

Long words broke the page on mobile:
Also removed border-radius for the code blocks in mobile:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix(ta): set up word breakes

---

apps/typescriptcourse/src/config.js
apps/typescriptcourse/src/pages/articles.tsx

Fixes the previous [fix](https://github.com/skillrecordings/products/pull/419) :
`og-image` attribute got duplicated.
after fix:

fix(typescriptcourse): fix og image

---

apps/testingaccessibility/src/templates/article-template.tsx

fix(testingaccessibility): break long word

---

apps/typescriptcourse/src/pages/articles.tsx
apps/typescriptcourse/src/pages/confirm.mdx
apps/typescriptcourse/src/pages/confirmed.mdx
apps/typescriptcourse/src/pages/excited.mdx
apps/typescriptcourse/src/templates/portable-text-article-template.tsx

<details>
</details>
<details>
</details>

fix(typescriptcourse): break long words + styles tweaks

---

apps/testingaccessibility/.gitignore
apps/testingaccessibility/package.json
apps/testingaccessibility/playwright/config/globalSetup.ts
apps/testingaccessibility/playwright/config/playwright.config.ts
apps/testingaccessibility/playwright/index.test.ts
apps/testingaccessibility/playwright/purchase.test.ts
apps/testingaccessibility/tsconfig.json
packages/convertkit-sdk/package.json
pnpm-lock.yaml

This adds rudimentary e2e tests for testing accessibility with no CI, just local.
run the tests which will run `start` script (but not `build`):
```bash
pnpm test:e2e
```
record tests by clicking around in the app which works with dev server running:
```bash
pnpm e2e:recorder
```

testing(ta): adds playwright tests

---

apps/testingaccessibility/src/pages/learn/index.tsx
apps/testingaccessibility/src/templates/module-template.tsx
apps/testingaccessibility/src/utils/progress.test.ts
apps/testingaccessibility/src/utils/progress.ts

we've had a couple reports from learners that weren't able to get a certificate even though they've clearly completed all sections in a module. this was due to some of the sections not having any lessons which caused progress measuring utility to skip them. this is fixed by including section without lessons in an array which then gets compared to user progress.

fix(ta): correctly determine section progress

---

apps/badass/src/templates/article-template.tsx

I realized that when someone shares an article from badass.dev the author was marcy, this small PR changes the author for @joelhooks

fixing the author for badass articles

---

apps/total-typescript/next.config.js
apps/total-typescript/src/components/exercise-overlay.tsx
apps/total-typescript/src/templates/exercise-template.tsx

example usage:
```
import {LoadingOverlay} from 'components/exercise-overlay'
{isVideoLoading && <LoadingOverlay />}
```

feat(tt): video loading overlay

---

apps/total-typescript/src/components/exercise-navigator.tsx
apps/total-typescript/src/components/exercise-overlay.tsx
apps/total-typescript/src/hooks/use-mux-player.tsx
apps/total-typescript/src/lib/exercises.ts
apps/total-typescript/src/lib/tips.ts
apps/total-typescript/src/lib/tutorials.ts
apps/total-typescript/src/pages/tips/[tip].tsx
apps/total-typescript/src/pages/tips/index.tsx
apps/total-typescript/src/pages/tutorials/[module]/[exercise]/index.tsx
apps/total-typescript/src/pages/tutorials/[module]/[exercise]/solution.tsx
apps/total-typescript/src/templates/exercise-template.tsx
apps/total-typescript/src/templates/tip-template.tsx
apps/total-typescript/src/templates/tutorial-template.tsx
apps/total-typescript/src/utils/get-next-exercise.ts
apps/total-typescript/studio/schemas/documents/exercise.js
apps/total-typescript/studio/schemas/documents/videoResource.js
apps/total-typescript/studio/schemas/objects/castingwordsTranscript.js
apps/total-typescript/studio/schemas/objects/resources/solution.js

fairly sweeping change with some minor updates to sanity, but the structure of the exercise query has changed to normalize properties like `stackblitz` and `muxPlaybackId` as properties of the exercise versus a sub-object.
the issue was that solution video resources were a reference and harder to get at, so this flattens everything to make it simpler.

feat(tt): updates exercise query for video resource

---

packages/create-skill-app/templates/next/next.config.js
packages/create-skill-app/templates/next/package.json

we want to stop using next-compose-plugins package in next config since it's not being updated

chore(csa): ditch `next-compose-plugins`

---

apps/testingaccessibility/src/pages/api/sanity/webhooks/add-all-records-to-algolia.ts
apps/testingaccessibility/src/pages/api/sanity/webhooks/add-records-to-algolia.ts
apps/testingaccessibility/src/utils/algolia/index.ts
apps/testingaccessibility/src/utils/algolia/sanity-algolia-client.ts

The server-side-only algolia client configured with the secret API write
key should only be imported into API code. Because it was being `*`
exported from the `utils/algolia/index.ts` file, it was being bundled
into the frontend code.
This was originally causing silent errors because the algolia client was
being configured with a blank value (that write key is only visible
servers-side). The schema parsing -- meant only to validate the key
server-side -- that I recently added was being triggered on the frontend
which caused that aforementioned error to fully surface.
This commit removes the re-export of the server-side algolia client.
Instead, the API code can import it directly from
`utils/algolia/sanity-algolia-client.ts`. Having to explicitly import it
form this location should help …

fix(ta): prevent default export of server-only code

---

apps/total-typescript/src/templates/exercise-template.tsx

Related to this issue: https://github.com/total-typescript/zod-tutorial/issues/15
It’s hard to say what exactly could be the reason of this behavior, can’t reproduce it on my side. I applied the change that could help “in theory” (just changed width: 100%  for flex-grow: 1 )

Fix screen flickers (probably)

---

apps/testingaccessibility/README.md
apps/testingaccessibility/package.json

According to a recent discussion, the `build:dev` command (introduced in [this PR](https://github.com/skillrecordings/products/commit/bf0fbe34244cd6414352b6f1308e05010313ecf1#diff-284649712bae897eb9f7e577e57534aa1ec714618f8b0b4641d70de63818c8ff))
is not used. Instead, if you want to build the app, you should run `pnpm
build`.
This commits removes `build:dev` from both `package.json` and the
`README.md` to avoid confusion about how to set up and build this app.

build(ta): remove `build:dev` from TA pnpm scripts

---

package.json
pnpm-lock.yaml

I read through the changelogs for the intervening versions (1.3.1 to 1.4.7) and I don't expect we need any manual changes.
---
This isn't the latest version, but gets us a lot closer to the latest
without requiring any changes to how we are using turbo.
One feature we can use after this bump is the `env` key for pipeline
tasks. https://github.com/vercel/turborepo/pull/1970

chore(deps): bump turbo to 1.4.7

---

apps/testingaccessibility/src/data/migrate-bulk-coupon-purchases-relation.ts
packages/commerce-server/src/record-new-purchase.ts
packages/database/prisma/schema.prisma
packages/skill-api/src/core/services/redeem-golden-ticket.ts

This PR represents the second and third step of the Expand and Contract
pattern for replacing the existing one-to-one relation between Bulk
Coupon and Bulk Purchase with a one-to-many relation of Bulk Coupon to
Purchases.
Before this can be merged, the schema needs to be fully deployed to the
existing production database environments. Those Deploy Requests have
already been opened at:
1. https://app.planetscale.com/skill-recordings/testing-accessibility/deploy-requests/14
2. https://app.planetscale.com/skill-recordings/total-typescript/deploy-requests/3
Visual of the one-to-many relationship we're moving toward:

feat(ta): add one-to-many relation for bulk coupons

---

apps/total-typescript/src/lib/sanity.ts
apps/total-typescript/src/pages/api/webhooks/sanity/videoResource/created.ts

For the next workshop, we are testing out a workflow where we order our transcripts using Whisper instead of Castingwords.
I've "unplugged" castingwords from the create sanity document handler so that we aren't paying for those transcripts to be done while we use Whisper.

feat(tt): disable castingwords order to test Whisper transcripts

---

apps/typescriptcourse/src/pages/podcast/[podcastSeason]/[podcastEpisode].tsx

Add subscriber form to podcast episode pages: 
The CTA is for starting the migration email course. This CTA can be made dynamic in the future, if we have other resources or podcast seasons that touch on other topics.

chore(typescript-course): add subscriber form to podcast section

---

apps/testingaccessibility/playwright/purchase.test.ts

1. Update path matcher for Stripe checkout session URL
2. Allow Stripe to redirect instead of visiting Thank You page for
hard-coded checkout session ID.

test(ta): fix e2e test for TA purchase flow

---

apps/testingaccessibility/src/pages/thanks/purchase.tsx

Post Purchase page was broken for individual purchases because Next.js cannot serialize `undefined`. Pass the value down as `null` instead.

fix(ta): cannot serialize undefined, pass null

---

apps/testingaccessibility/src/pages/team/buy-more-seats.tsx
packages/database/src/prisma-api.ts

This feature was less involved than I originally anticipated. I thought it would require schema changes. It doesn't. And because of how we are already processing new and existing bulk purchases, this page can handle seat buying for both individuals and existing teams.
Roam Notes: https://roamresearch.com/#/app/egghead/page/bIpYsr441
---
This adds a page that a logged in user with a purchase can visit. It has
a 'Buy More Seats' component that takes the user to a Stripe Checkout
Session. Once they complete the purchase, a new Bulk Coupon will be
created for the user with that many seats. It doesn't impact their
existing individual purchase, which we maintain for record keeping and
to determine this user's access.
There is no top-level UI for accessing this page. Support can link a person …

feat(ta): allow Individual to upgrade to Team

---

apps/protailwind/src/components/navigation.tsx
apps/protailwind/src/pages/tips/index.tsx

This small PR adds a `px-5` class to the header of the Tips page, to make sure the text doesn't touch the edges of the viewport on small screens.
I also made the hover state for the nav links a tiny bit darker (`bg-gray-100` instead of `gray-50`).

fix(pt): tips page header padding + nav links hover state

---

packages/commerce-server/src/record-new-purchase.ts
packages/stripe-sdk/.eslintrc.js
packages/stripe-sdk/.gitignore
packages/stripe-sdk/package.json
packages/stripe-sdk/process.d.ts
packages/stripe-sdk/src/index.ts
packages/stripe-sdk/src/stripe-client-context.ts
packages/stripe-sdk/src/stripe-sdk.ts
packages/stripe-sdk/tsconfig.json
packages/stripe-sdk/tsup.config.ts
pnpm-lock.yaml

[⭐️ long 45m end-to-end loom video of creating this PR](https://www.loom.com/share/28d14ea87b7b410092abd70d74d8bcb6)
we are exploring how to mock out services to test some of our commerce workflows. In this PR, I looked at how we were mocking `prisma` in the `@skillrecordings/database` package utilizing a database SDK that wraps `prisma` in a lightweight typed mockable context using `jest-mock-extended`
This PR introduces `@skillrecordings/stripe-sdk` which provides a similar mockable context for testing stripe without using a heavier solution for now using simple data objects as mocks.
We should consider moving **all `stripe` calls** into this SDK instead of accessing the `stripe` library across the entire application and package surface area.
IMO, this is true for these service …

feat: creating a stripe sdk for simplified mocking

---

packages/commerce-server/src/record-new-purchase.ts
packages/database/src/prisma-api.ts

The bulk coupon always gets created along with the purchase if it is a
purchase of a bulk coupon (or bulk coupon addition), so it makes sense
to push that up into the `createMerchantChargeAndPurchase` function.
This has the added benefit of removing the remaining direct Prisma DB
calls from the recordNewPurchase module.

feat(db): move bulk coupon create into SDK

---

apps/total-typescript/src/ability/ability.ts

Using the tests that @joelhooks recently added for the Ability files to do some refactoring. My goal was to make the logic clearer and to remove some redundancy in the checks.
- cleanup(tt): remove unused Ability imports
- cleanup(tt): rearrange and clarify Ability logic
The git diff looks messy, but the resulting _determine rules block_ looks much cleaner at a glance.

cleanup(tt): clarify logic and removed unused imports in Ability

---

apps/testingaccessibility/src/pages/thanks/purchase.tsx
apps/total-typescript/src/pages/thanks/purchase.tsx

I noticed this path typo which started in TA and was copied into TT. This fixes both spots.
Roam: https://roamresearch.com/#/app/egghead/page/10mtvqNw8

fix: path to Team Invite should be `/team`

---

apps/typescriptcourse/src/pages/index.mdx

This fixes a minor typo of `className` on the index page.

fix: typo in index.mdx TypeScript Course

---

apps/total-typescript/src/pages/team/buy-more-seats.tsx

This works the same way it does in Testing Accessibility.
- We use a separate "Buy More Seats" page that anyone with an existing purchase/user can  use.
- There is no top-level navigation to this page.
- This page can be explicitly linked to by support or email on a customer to customer basis.
Roam: https://roamresearch.com/#/app/egghead/page/VLioXKScO

feat(tt): allow Individual to upgrade to Team

---

apps/total-typescript/src/ability/ability.test.ts
apps/total-typescript/src/ability/ability.ts

Look more closely at the details of the purchase records. If a purchase
record is only the bulk purchase and not a redemption or individual
purchase, then the user should not be able to view content.
Attempting to make the check that @vojtaholik was working on in https://github.com/skillrecordings/products/pull/634
We can determine if a user should have access based on whether they have a purchase that isn't just a bulk coupon purchase (i.e. it does not have a `bulkCouponId`). This works for both individual purchases and bulk coupon redemptions, as you can see in this Arctype screenshot.

feat(tt): check purchase details for lesson access

---

apps/total-typescript/src/components/exercise-overlay.tsx
apps/total-typescript/src/components/exercise/exercise-description.tsx
apps/total-typescript/src/components/exercise/github-link.tsx
apps/total-typescript/src/templates/exercise-template.tsx

improve(tt): block body copy on lesson pages

---

apps/total-typescript/src/pages/invoices/[merchantChargeId].tsx
packages/commerce-server/src/prisma-next-serializer.ts

Some refactoring based on my comments in https://github.com/skillrecordings/products/pull/632
- feat: serialize objects recursively for Next
- refactor(tt): use existing SDK function
- refactor(tt): eliminate unnecessary query

refactor(tt): use existing `getPurchaseForStripeCharge` function

---

apps/total-typescript/src/path-to-purchase-react/pricing.tsx
apps/total-typescript/src/styles/pricing.css
apps/total-typescript/src/team/buy-more-seats.tsx

The Buy page has a component with some custom styling for display the
formatted price along with any discount being applied. This attempts to
extract that as a component that can be used in the 'Buy More Seats'
component as well.
WIP: while this is pretty close to what we need -- I think the logic / mechanics are all in place -- the styles don't work well in both places.
@vojtaholik any ideas for how to get these styles working in both places? Or is this where the component sharing breaks down for this example and the styles need to be separated?

feat(tt): share pricing display logic across app

---

apps/engmanagement/src/components/team/self-redeem-button.tsx
apps/kcdbundle/src/pages/buy/email.tsx
apps/testingaccessibility/src/components/team/copy-invite-link.tsx
apps/testingaccessibility/src/components/team/index.tsx
apps/testingaccessibility/src/components/team/self-redeem-button.tsx
apps/total-typescript/src/offer/survey/survey-question.tsx
apps/total-typescript/src/team/copy-invite-link.tsx
apps/total-typescript/src/team/index.tsx
apps/total-typescript/src/team/self-redeem-button.tsx
packages/quiz/src/components/question/index.tsx
packages/react/src/components/button/index.tsx

This gets rid of the old 'buy more seats' button that conditionally
displays when there are no more seats. We can instead rely on the 'Buy
More Seats' widget below this that is always visible.
It also adds a disabled attribute and disabled styles to the various
team buttons, instead of hiding them, to make it clearer what is
available if you get more seats.
https://user-images.githubusercontent.com/694063/207927412-83204784-8824-40d3-ae63-cc07ebffc711.mp4
https://user-images.githubusercontent.com/694063/207927470-4b4ee89a-0d68-4ff5-b0d9-4d2e11c3a496.mp4

feat: improve 'out of seats' state of Team page

---

apps/total-typescript/src/path-to-purchase-react/pricing.tsx

This PR adds a link to the Buy page, if you've already purchased, that links you to the Buy More Seats page. This way we don't dead-end users on the Buy page when they want to upgrade to a team or get more seats for their team.

feat(tt): add Buy More Seats to Buy page

---

apps/total-typescript/src/pages/thanks/purchase.tsx

This should hopefully go well with and make it easier to do what is described in https://linear.app/skillrecordings/issue/TT-25/add-link-to-invoice-on-thanks-page. In fact, I noted a place in the JSX where the invoice link could be slotted in.
Here is what each of the post-purchase scenarios look like:

feat(tt): separate post-purchase scenario components

---

apps/total-typescript/src/path-to-purchase-react/pricing.tsx
apps/total-typescript/src/server/routers/pricing.ts
apps/total-typescript/src/team/buy-more-seats.tsx

instead of relying on the client to carry the user's purchases around,
we can just look them up on demand.

feat(tt): load purchases in pricing endpoint

---

apps/protailwind/src/components/exercise-navigator.tsx
apps/protailwind/src/components/exercise-overlay.tsx
apps/protailwind/src/components/portable-text/index.tsx
apps/protailwind/src/hooks/use-mux-player.tsx
apps/protailwind/src/pages/tutorials/[module]/[lesson]/index.tsx
apps/protailwind/src/pages/tutorials/[module]/[lesson]/solution.tsx
apps/protailwind/src/templates/tutorial-template.tsx
apps/total-typescript/src/components/exercise-overlay.tsx
apps/total-typescript/src/components/exercise/github-link.tsx
apps/total-typescript/src/components/exercise/stackblitz-iframe.tsx
apps/total-typescript/src/pages/tutorials/[module]/[lesson]/index.tsx
apps/total-typescript/src/pages/tutorials/[module]/[lesson]/solution.tsx
apps/total-typescript/src/pages/workshops/[module]/[section]/[lesson]/index.tsx
apps/total-typescript/src/pages/workshops/[module]/[section]/[lesson]/solution.tsx
apps/total-typescript/src/templates/exercise-template.tsx
apps/total-typescript/src/templates/tutorial-template.tsx
apps/total-typescript/src/templates/workshop-template.tsx
apps/total-typescript/src/video/lesson-list.tsx
packages/skill-lesson/hooks/use-mux-player.tsx

this is a sweeping route change in modules renaming `[exercise]` as `[lesson]` where an `Exercise` is a specific type of lesson and the `[lesson]` route supports a number of different shapes of `LessonResource`

chore(pt): switch route param from `exercise` to `lesson`

---

packages/database/src/prisma-api.ts
packages/skill-api/src/core/services/redeem-golden-ticket.ts

When either a bulk coupon (single-seat) or a non-bulk coupon is
redeemed, we need to tie the $0 purchase record to that coupon.

fix(tt): record bulk and non-bulk coupon relation

---

packages/skill-lesson/hooks/use-mux-player.tsx

this prevents content from being non-interactive when finishing a video in fullscreen mode by proactively exiting it. 
likely not ideal, but I couldn't figure out how to prevent default muxplayer's behavior and target its container as fullscreen wrapper to make it so video overlays could persist with fullscreen mode turned on. I tried listening for `onfullscreenchange` event on muxplayer's ref in combination with `e.preventDefault()` but that didn't work (weird).

feat(tt): exit fullscreen on video ended

---

packages/skill-lesson/hooks/use-next-lesson.ts
packages/skill-lesson/lib/lesson-resource.ts
packages/skill-lesson/server/routers/lessons.ts

we can't query for solutions in sanity and need to query their container exercise instead so this uses the route param

solutions need the slug of their container exercise to get next lesson

---

packages/skill-lesson/hooks/use-global-player-shortcut.ts

fix(skill-lesson): global shortcuts should ignore content editable elements

---

apps/badass/package.json
apps/epic-web/package.json
apps/protailwind/package.json
apps/skillrecordings/package.json
apps/testingaccessibility/package.json
apps/total-typescript/package.json
apps/typescriptcourse/package.json
package.json
packages/convertkit-react-ui/package.json
pnpm-lock.yaml

The Sanity v3 Studio that gets generated by the create-skill-app package is not able to run a development server. When you start it up, it immediately fails because of a bad import statement in a mismatched dependency.
I tracked this mismatched dependency down. Because of having several different versions of framer-motion throughout the various packages and apps, we get into a situation where motionone/dom 10.11.0 is being mixed with motionon/animation 10.14.0. The difference in those minor versions is an import getting moved around.
To fix this, we can run manypkg to update framer-motion. E.g.:
```
$ pnpm manypkg update framer-motion
```
This depends on `manypkg` having been added as a script in the top-level `package.json`.

chore(deps): use manypkg to upgrade framer-motion

---

apps/protailwind/src/pages/tutorials/[module]/[lesson]/exercise.tsx
apps/protailwind/src/pages/workshops/[module]/[section]/[lesson]/exercise.tsx
apps/protailwind/src/video/lesson-list.tsx
apps/total-typescript/src/pages/tutorials/[module]/[lesson]/exercise.tsx
apps/total-typescript/src/pages/workshops/[module]/[section]/[lesson]/exercise.tsx
apps/total-typescript/src/video/exercise-overlay.tsx
apps/total-typescript/src/video/lesson-list.tsx
apps/total-typescript/src/video/video.tsx
packages/skill-lesson/hooks/use-mux-player.tsx
packages/skill-lesson/hooks/use-next-lesson.ts

there's definitely more ways to approach this and I'm open for suggestions. this approach consists of a single check inside  effect and new `/exercise` route.
https://user-images.githubusercontent.com/25487857/217041615-7bd9ac31-2fbe-48b5-a5e3-081de3499b12.mp4

feat(tt): make repls navigatable

---

apps/protailwind/src/components/icons.tsx
apps/protailwind/src/pages/purchases/[purchaseId].tsx
apps/protailwind/src/pages/purchases/index.tsx
apps/protailwind/src/pages/welcome/index.tsx
apps/protailwind/src/purchase-details/purchase-details-template.tsx
apps/protailwind/src/purchase-details/purchase-details.css
apps/protailwind/src/purchase-details/purchases-index-template.tsx
apps/protailwind/src/purchase-transfer/purchase-transfer.tsx
apps/protailwind/src/styles/globals.css

- display transfer purchase UI on `purchases/[purchaseId]` pages
- move `purchases` route templates into separate directory inside `src`
- add ability to style transfer purchase ui separately (theming)
- polish styles

update(pt): display transfer purchase ui on purchase page and polish its ui

---

apps/protailwind/studio/sanity.json
apps/protailwind/studio/yarn.lock
apps/total-typescript/studio/sanity.json

I wanted to experiment with queries today with our data but I saw that vision wasn't currently being used. This includes the plugin for both the Pro Tailwind and Total TypeScript studios

Add Vision Plugin to Pro Tailwind and Total TypeScript studios

---

apps/protailwind/studio/schemas/documents/module.js

Now that all modules have their content within sections, we can make this adjustment to the schema.

Pro Tailwind - only allows for sections and products in module schema

---

packages/commerce-server/src/record-new-purchase.ts
packages/database/src/prisma-api.ts
packages/stripe-sdk/src/stripe-sdk.ts

More details in Roam (https://roamresearch.com/#/app/egghead/page/R83NFE69j) and the linear issue.
Essentially, there was nothing in place before this to attempt to tie a purchase's `Coupon` record to a corresponding Stripe `MerchantCoupon`.
I just tested this out with a 5% off bulk purchase locally and it is now tying those records together as expected.

feat(tt): if a Stripe coupon is used, record it

---

apps/testing-javascript/src/data/lesson-progress-import.ts
apps/testing-javascript/src/data/purchase-import.ts

These scripts will import the Purchase data and Lesson Progress data for
Testing JavaScript into the Planetscale database. These scripts target
JSON files that were created by rake task exports located in the
egghead-rails codebase.
This PR includes two scripts:
1. Imports all Purchase, User, Coupon, Merchant Charge, Merchant Customer data
2. Imports all Lesson Progress data
The reason these are split out is that 1 is more critical data, whereas the app could function (temporarily) without Lesson Progress. And the lesson progress export is massive (~600k records) relative to the other export.
There are details in each script about how to run them. The idea is that they would be run back-to-back during a hard cutover from the old site and database to the new site and database.
More details …

feat(kcd): add scripts for importing TJS data

---

.kodiak.toml

We've had the convention of 'rfc' being a no-merge tag in other
repositories. I was surprised that a recent 'rfc' PR got merged. If
your PR is a 'request for comment', then you are likely not looking to
merge yet, so I'd like to preserve that convention.

config: add 'rfc' tag to Kodiak no-merge list

---

apps/testing-javascript/src/data/sanity-import.ts

I already used this updated script to re-import the production Sanity data. This PR is to get those changes under version control.
- feat(kcd): ignore specific duplicate TJS courses
- feat(kcd): scrub WEBVTT from top of SRT text

Remove duplicate Workshops from Testing JavaScript Sanity Import

---

apps/total-typescript/src/templates/exercise-template.tsx

The explainers showed an empty GitHub link from the changes made on #861. 
This PR adds the logic only to show the GitHub button when added in Sanity!

fix(tt): fix github link for explainers

---

apps/epic-react/src/components/lesson-listing.tsx
apps/epic-react/src/components/module-listing.tsx
apps/epic-react/src/lib/modules.ts
apps/epic-react/src/pages/[module]/index.tsx
apps/epic-react/src/pages/learn.tsx

This updates the module page to include a listing of the sections and lessons contained within that module. It also displays the module's body using the Portable Text (for react) component. And the module page is linked to from the learn page.
Like https://github.com/skillrecordings/products/pull/909, I'm just making sure the main/essential pieces are available and in place, fully porting over the look, feel, and behavior will happen in follow up work.

feat(kcd): add module page, link to it

---

apps/protailwind/src/components/page-headline.tsx
apps/protailwind/src/components/page-subheadline.tsx
apps/protailwind/src/pages/articles.tsx
apps/protailwind/src/pages/buy.tsx
apps/protailwind/src/pages/confirm.tsx
apps/protailwind/src/pages/tips/index.tsx
apps/protailwind/src/pages/tutorials/index.tsx
apps/protailwind/src/pages/workshops/index.tsx
apps/protailwind/src/purchase-details/purchases-index-template.tsx
apps/protailwind/src/templates/article-template.tsx

This PR also fixes a duplicated `key` on the `/buy` page since both products had the same `product.name`.
Oh, and adds the little love heart hover effect on the signature in the article pages!

chore(pt): standardise page headline, subheadline and button links

---

apps/epic-react/src/data/transfer-lesson-progress-from-local-db-to-planetscale.ts

This script synchronously transfers records from a local LessonProgress
table to a remote Planetscale LessonProgress table. Because of
consistent connection failures during the multi-threaded streaming
approach, I decided to go another direction with this. With this script,
we always know how far we've processed through the table of records, so
if the connection gets closed, we can record where we are, and pick up
where we left off. This makes the script idempotent which means that it
can be run outside of the cutover processes after the site has been
brought back up. The original import script will still need to be run
first in order to load those records up into a local Docker database.
If a connection gets closed, which happens quite often with planetscale,
then this script will note …

jb/er 28 rework Lesson Progress import script to be fault tolerant

---

apps/total-typescript/src/styles/shiki-twoslash.css

Made shiki-twoslash css prettier for errors and hovers

---

apps/protailwind/src/lib/tips.ts
apps/protailwind/src/pages/tips/index.tsx

The auto-generated thumbnails are not that aesthetically pleasing, so I opted for a layout that de-emphasizes them and makes the content quicker to scan.
New tips ordered first, too 👍

chore(pt): tips page -> smaller thumbnails, order with newest first

---

packages/skill-lesson/lib/castingwords.ts

all transcripts are being stored as `text` so we can do this now :)

chore: stop writing transcript as PT

---

turbo.json

The `!.next/cache/**` directory isn't needed at deploy time so storing this in your Remote Cache can:
1. Make the artifacts you're keeping significantly larger than they need to be
2. Take longer to upload
This directory is mostly for making compilation faster at development time - and it's pretty chonky. You shouldn't need it when you're deploying!
Notably, we've updated our guidance around this from being `[".next/**"]` in the docs in the past. You'll see it [here](https://turbo.build/repo/docs/core-concepts/caching/what-to-cache#exclusions) and  [everywhere](https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#turborepo-can-multitask) [else](https://turbo.build/repo/docs/ci/github-actions) in the docs today.

Exclude `.next/cache/**` from build outputs

---

apps/testing-javascript/src/path-to-purchase/pricing.tsx

I added in the `minimalFractionDigits` option for the [currency NumberFormat constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) set to `2` so that we get `80` instead of `8` when the discounted price has cents involved.

feat(tjs): improve currency formatting of cents

---

apps/testing-javascript/process.d.ts
apps/testing-javascript/src/pages/index.tsx

cleanup(tjs): use product ID from env vars

---

apps/protailwind/src/lib/articles.ts
apps/protailwind/src/pages/articles.tsx

Added post date, removed `shortDescription`, cleared used `summary` instead of `description` since the `description` (SEO meta) might want to be decoupled from what shows on the listing card.

pt(chore): Articles list fields and cards tweaks

---

packages/skill-api/src/core/services/convertkit/convertkit-tag-purchase.ts

I was getting this error about the CK purchase tag ID needing to be set. I don't think we want to be sending tagging events to CK in development, so I'm checking the `NODE_ENV` and exiting this function early if we are in `development`.

feat: skip CK tagging in development

---

packages/commerce-server/src/format-prices-for-product.test.ts
packages/commerce-server/src/format-prices-for-product.ts

if regional pricing criteria are met, then PPP coupon is available for users:
- with no purchase
- that previously made a purchase using PPP coupon
I also tested a different solution which only disabled PPP for upgradeProduct (in this case a react bundle), but then the standalone product would be less expensive with PPP then the upgrade itself. So I decided to turn it off on all tiers.

feat(commerce): PPP coupon not available for non-ppp purchasers

---

apps/badass/src/lib/case-studies.ts

Adjusted query so that only published case studies get fetched.

badass.dev: fetch published case studies only

---

apps/total-typescript/src/templates/purchased-product-template.tsx
packages/skill-lesson/index.tsx
packages/skill-lesson/path-to-purchase/pricing.tsx
packages/skill-lesson/team/buy-more-seats.tsx
packages/skill-lesson/utils/build-stripe-checkout-path.ts

This commit also includes a refactor of how we are building the Skill
API stripe checkout path for form submission. It consolidates the
parameter building, adds type-checking, and uses URLSearchParams.
Example of the bulk coupon not being passed to Stripe:
Now, it is being passed in:

fix(tt): pass applied bulk coupon to Stripe

---

apps/scriptkit/src/team/buy-more-seats.tsx
apps/testingaccessibility/src/components/pricing.tsx
apps/testingaccessibility/src/components/team/buy-more-seats.tsx
apps/total-typescript/src/templates/purchased-product-template.tsx
packages/commerce-server/src/@types/index.ts
packages/commerce-server/src/determine-coupon-to-apply.ts
packages/commerce-server/src/format-prices-for-product.ts
packages/skill-lesson/team/buy-more-seats.tsx

The FormattedPrice should indicate to consumers whether the purchase is
going to be a bulk purchase or not. This is because the price formatting
logic does a qualified seat count lookup and knows if the purchase is
individual or adding to an existing bulk purchase.
Existing logic might think a purchase of `quanity = 1` is an individual
purchase when in fact a single seat is being added to an existing bulk
purchase.

feat(commerce): indicate bulk purchase in price

---

packages/skill-lesson/trpc/routers/pricing.ts

If you've already purchased the upgrade (e.g. from Core to Bundle), then
we shouldn't be re-identifying the Bundle upgrade as an *available*
upgrade. You can't purchase the upgrade twice, so it isn't available.
This now checks against all your existing purchases before passing along
a potential upgrade opportunity.

feat(commerce): exclude already purchased upgrade

---

packages/skill-api/src/core/services/convertkit/subscribe-to-convertkit.ts

full ck subscriber object includes all the fields even the empty/null ones by default. cookie value cannot be more than 4096 chars which we were exceeding on TT, resulting in subscriber cookie not being set, and users not being able to watch tutorials after subscribing.
This is a quick fix and we should investigate more deeply into whether `fullSubscriber` object is required in a cookie since this can happen again even after this is merged.
Fixes TT-341

update(ck): filter out null values from `fullSubscriber`

---

packages/skill-lesson/trpc/routers/module-progress.ts

fixes #1116 
Linear issue: https://linear.app/skillrecordings/issue/TT-342/app-should-gracefully-handle-duplicate-lessonprogress-records

fix: deduplicate lesson progress data

---

packages/commerce-server/src/record-new-purchase.ts
packages/database/src/prisma-api.ts
packages/skill-api/src/core/services/stripe-checkout.ts

We have the `upgradedFromId` on the `Purchase` table which exists to
record when a Purchase record is one that was upgraded from an existing
Purchase record. We haven't been using it tho.
This includes that info in the Stripe metadata during the checkout phase
when we have easy access to the purchase being upgraded from and then in
the post-purchase handler, we record that on the new purchase record.
The reason this is useful beyond just generally doing record keeping and knowing what is connected is that we can use the info in order to determine a chain of purchases in order to accurate compute the fixed discount to be applied in certain scenarios (https://linear.app/skillrecordings/issue/TT-338/ppp-to-unrestricted-upgrade-for-a-multi-purchase-bundle-is-not).
As an example, if I purchase …

feat(commerce): record upgradedFromId on purchase

---

packages/commerce-server/src/format-prices-for-product.test.ts
packages/commerce-server/src/format-prices-for-product.ts

When we compute the fixed discount for a PPP to Unrestricted upgrade, we
have been assuming that the _Purchase to be Upgraded_ is the only
purchase. However, it is possible that someone purchase Core(PPP), then
purchased an upgrade to Bundle(PPP), and now wants to upgrade to
Unrestricted Bundle. In that case, we need to get the _amount paid_ for
each of the purchases in the chain of purchases when computing the fixed
discount, otherwise we are overcharging the user.

feat(commerce): multi-purchase fixed discount

---

packages/commerce-server/src/@types/index.ts
packages/commerce-server/src/format-prices-for-product.ts
packages/skill-lesson/path-to-purchase/pricing.tsx

The `fixedDiscount` value that is computed in the price formatter
is the value we want to be displaying when there is a 'credit applied',
so this now passes that value along. Before we were only display an
applied credit based on the unit price of the purchase which doesn't
factor in PPP.

fix(commerce): display correct Applied Credit amt

---

apps/testing-javascript/src/@types/index.ts
apps/testing-javascript/src/components/playlist/playlist-item.tsx
apps/testing-javascript/src/lib/lessons.ts
apps/testing-javascript/src/lib/playlists.ts
apps/testing-javascript/src/lib/secondsToFormattedTime.ts
apps/testing-javascript/src/pages/playlists/[module].tsx
apps/testing-javascript/src/templates/workshop-template.tsx

Use values now available in Sanity along with time-formatting helper to display Module and Lesson duration throughout the site.
@DrShpongle should the Lesson duration also show in the individual lesson page itself?

feat(tjs): display duration of Modules/Lessons

---

packages/commerce-server/src/determine-coupon-to-apply.ts
packages/commerce-server/src/format-prices-for-product.test.ts
packages/commerce-server/src/format-prices-for-product.ts
packages/skill-api/src/core/services/load-prices.ts
packages/skill-lesson/path-to-purchase/pricing.tsx
packages/skill-lesson/trpc/routers/pricing.ts

This PR takes advantage of the work done in #1117 to know whether PPP is being applied and if we should show or hide the checkbox.
This PR still includes the work done to make the Price Formatter configurable. The call site can request PPP to be not be auto-applied if it would like (test included), though we choose to always auto-apply for now.
Here is a screenshot of upgrading from Core(PPP) to Bundle(PPP). The PPP discount is auto-applied and the checkbox is hidden.

PPP checkbox shouldnt show when bundle ppp discount is auto-applied

---

apps/testing-javascript/src/components/playlist/playlist-item.tsx
apps/testing-javascript/src/lib/playlists.ts

The groq query that fetches all the playlists for the homepage should
include the Mux playback ID for each of the module intros so that inline
preview players can show those to unauth'd users.
This is instead of having the Backend module's Mux playback ID hardcoded for all of these.

feat(tjs): include intro Mux playback ID w/ GROQ

---

apps/testing-javascript/src/templates/landing-template.tsx

The original mux upload that I did for the course intro video was not
using the highest quality original video. This changes it to a new
upload that uses the original.

feat(tjs): use original video for mux intro upload

---

apps/testing-javascript/src/pages/thanks/redeem.tsx

On the post-redeem page, I wasn't able to see the text. That is because it is white-on-white.
The highlighting (`selection-...`) was also behaving weirdly, so I removed those classes.

fix(tjs): make text visible on post-redeem page

---

apps/testing-javascript/src/pages/index.tsx
apps/testing-javascript/src/styles/globals.css
apps/testing-javascript/src/styles/redeem-dialog.css

*Update*: This PR is now ready to go. A new user can now redeem a team invite.
---
This is a WIP. The `redeem-dialog.css` styles aren't being applied to
the radix dialog components and so the overlay and dialog are not
appearing.
To reproduce:
1. Log in as a team owner or create a team owner by making a multi-seat purchase
2. Go to the `localhost:3018/team` page and find the Invite Team link
3. Open that link in a separate browser/incognito mode
4. ... notice the dialog doesn't appear, but the overlay does take control of the page, you can't scroll
@DrShpongle any help you could provide on this would be greatly appreciated.

feat(tjs): add in team coupon redemption dialog

---

apps/epic-web/src/pages/get-started/index.tsx

I make this mistake all the time 😅

chore: fix foundations URL

---

apps/testing-javascript/src/templates/lesson-template.tsx
apps/testing-javascript/src/trpc/routers/_app.ts
apps/testing-javascript/src/trpc/routers/products.ts

The `getDefaultProduct` function uses `getActiveProduct` which is
defined in a bespoke way for TJS (grabs specific data needed from that
Sanity instance). Instead of shuffling all that into `skill-lesson`,
this adds a custom products router that doesn't collide with the one
defined in `skill-lesson`.

feat(tjs): allow TJS its own products router

---

apps/testing-javascript/src/data/replace-transcript-text.ts

This pairs with https://github.com/skillrecordings/products/pull/1250 which turned the transcript field from PortableText into plain Text which can easily hold the markdown format of the enhanced transcripts.
The script in this PR then overwrites the transcript fields with the enhancedTranscript markdown exported from the egghead-rails database.
**I've already run this script against production TJS sanity and it updated the transcripts as desired.**

feat(tjs): replace transcript with enhanced

---

apps/testing-javascript/schemas/documents/interview.tsx

The Sanity schema for interviews has all the other metadata for the TJS interviews, but is missing a way to attach a `videoResource`. This adds it.
Once this is merged and deployed, I'll follow it with a script that will inject Mux-backed videos into each interview.

feat(tjs): add video resource to TJS interviews

---

apps/testing-javascript/schemas/documents/interview.tsx

The Portable Text data type is conflicting with the expectations of
parsing logic in skill-lesson (e.g. useNextLesson).
Since there are only 10 small descriptions, I am going to manually copy the text over once this schema change is merged and deployed.

feat(tjs): switch interview descriptions to text

---

apps/testing-javascript/schemas/documents/module.jsx

The `skill-lesson` package expects to be able to look up a module for an
interview when it is trying to figure out the "Next Lesson". So I'm adding
`Interview` as a Resource-type so that I can create an _Expert Interviews_
module.

feat(tjs): allow Interview as part of Module

---

apps/testing-javascript/package.json
apps/testing-javascript/src/@types/index.ts
apps/testing-javascript/src/components/landing/interviews.tsx
pnpm-lock.yaml

Since these were switched from PortableText to Markdown (plain text), these two spots needed to be updated to markdown-rendering instead of PT-rendering.

feat(tjs): render Interviewer descriptions as md

---

apps/testing-javascript/schemas/documents/explainer.js

TJS has three kinds of code URLs, this allows for each kind of those to
be stored. We store them independently because they are each treated a
little differently and the two github ones can both be present for the
same lesson.

feat(tjs): add code URLs to Sanity lesson schema

---

apps/testing-javascript/src/components/lessons-sidebar.tsx
apps/testing-javascript/src/server/lessons.server.ts
apps/testing-javascript/src/styles/code.css
apps/testing-javascript/src/styles/globals.css
apps/testing-javascript/src/styles/miscellaneous.css
apps/testing-javascript/src/templates/lesson-template.tsx
apps/testing-javascript/src/trpc/routers/_app.ts
apps/testing-javascript/src/trpc/routers/lessons.ts
packages/skill-lesson/video/video-transcript.tsx

- feat(tjs): specify types for Lesson Sidebar
- cleanup(tjs): remove unused imports
- feat(tjs): make placeholder to display description
- feat(tjs): load and render code URLs
- feat(tjs): render codesandbox url to iframe
- feat(tjs): add styles for code section
Here are URLs for the different scenarios:
- CodeSandbox embed: http://localhost:3018/lessons/javascript-support-async-tests-with-javascripts-promises-through-async-await
- Just a link to a github branch: http://localhost:3018/lessons/javascript-intro-to-static-analysis-testing-javascript-applications
- Link to github branch AND to a github diff: http://localhost:3018/lessons/javascript-lint-javascript-by-configuring-and-running-eslint
There are a few styling issues that need to be resolved. Here is what it looks like as of this …

Display github URLs and codesandbox embeds for TJS

---

apps/testing-javascript/schemas/documents/explainer.js
apps/testing-javascript/src/data/replace-interview-descriptions.ts
apps/testing-javascript/src/templates/lesson-template.tsx

- feat(tjs): replace PT body with markdown
- feat(tjs): use `lesson.body` for description
Once this is merged I will need to:
- Deploy the schema change to production Sanity
- Run the data migration script to replace the PT body with markdown body
- Verify lesson descriptions are rendering appropriately

Replace PortableText lesson body with text for Lesson Description

---

apps/testing-javascript/src/lib/lessons.ts

These were leftover concepts from TT when pulling in some of that logic,
they are not relevant to the TJS Sanity data model, so they can be
removed from the lesson groq queries.

feat(tjs): remove excess values from groq queries

---

apps/colt-steele/src/utils/sanity-client.ts
apps/epic-react/src/data/sanity-import.ts
apps/epic-web/src/utils/sanity-server.ts
apps/protailwind/src/utils/sanity-server.ts
apps/scriptkit/src/utils/sanity-client.ts
apps/scriptkit/src/utils/sanity-server.ts
apps/technical-interviews/src/utils/sanity-client.ts
apps/testing-javascript/src/data/add-duration-to-sanity.ts
apps/testing-javascript/src/data/add-videos-to-sanity-interviews.ts
apps/testing-javascript/src/data/sanity-import.ts
apps/testing-javascript/src/utils/sanity-client.ts
apps/testingaccessibility/src/utils/sanity-client.ts
apps/typescriptcourse/src/utils/sanity-server.ts
packages/skill-api/src/lib/sanity-client.ts

The default export from `@sanity/client` is deprecated as a method for
creating a client instance, and `createClient` should be used going
forward. This refactor will clean up a bunch of errors/warnings in the
logs.

refactor: use Sanity createClient everywhere

---

apps/epic-web/schemas/documents/product.tsx
apps/epic-web/src/inngest/events/sanity.ts
apps/epic-web/src/inngest/functions/sanity/product.ts
apps/epic-web/src/inngest/functions/sanity/product/index.ts
apps/epic-web/src/inngest/functions/sanity/product/sanity-product-created.ts
apps/epic-web/src/inngest/functions/sanity/product/sanity-product-deleted.ts
apps/epic-web/src/inngest/functions/sanity/product/sanity-product-updated.ts
apps/epic-web/src/inngest/inngest-config.ts
apps/epic-web/src/inngest/inngest.config.ts
apps/epic-web/src/lib/products.ts
apps/epic-web/src/pages/api/inngest.ts
apps/epic-web/src/utils/sanity-server.ts
packages/database/src/client.ts

Took a look at the Sanity syncing workflow and wanted to make some changes to the flow.
Could use some help:
[🚌 1 hour struggle bus loom design and implementation session](https://www.loom.com/share/a67fc3e5336c44aea89e5d4abd3c258d?sid=13490684-7df8-4a7d-8694-29d61f563289)

feat: product sync sanity -> skill -> stripe

---

apps/colt-steele/src/pages/api/webhooks/sanity/videoResource/created.ts
apps/epic-web/src/pages/api/webhooks/sanity/videoResource/created.ts
apps/pro-nextjs/src/pages/api/webhooks/sanity/article/updated.ts
packages/skill-api/src/core/services/process-sanity-webhooks.ts
packages/skill-lesson/lib/sanity.ts

`isValidSignature` from `@sanity/webhook` returns type of `Promise<boolean>` thus has to be awaited.

fix(builds): await isValidSignature in sanity webhook

---

apps/colt-steele/src/styles/video/video-overlays.css
apps/epic-web/src/styles/video/video-overlays.css
apps/pro-nextjs/src/styles/video/video-overlays.css
apps/total-typescript/src/styles/video/video-overlays.css
packages/skill-lesson/video/video-overlays.tsx
packages/ui/primitives/progress.tsx

This refactors `skill-lesson`'s video overlays and involved applications (TT, EW, CS and PNJS) to use shared Progress component.
Also some unused styles are cleaned up.
@joelhooks `TJS` doesn't use progress currently. Do we want to implement it?
<details>
<summary>Colt Steele (default):</summary>
</details>
<details>
<summary>Colt Steele (finished):</summary>
</details>
<details>
<summary>EpicWeb (default):</summary>
</details>
<details>
<summary>EpicWeb (finished):</summary>
</details>
<details>
<summary>ProNextJS (default):</summary>
</details>
<details>
<summary>ProNextJS (finished):</summary>
</details>
<details>
<summary>Total Typescript (default):</summary>
</details>
<details>
<summary>Total Typescript (finished):</summary>
</details>

refactor(skill-lesson): use Progress primitive

---

apps/epic-react/src/components/app/layout.tsx
apps/epic-react/src/pages/api/inngest.ts
apps/epic-react/src/templates/tip-template.tsx
packages/create-skill-app/templates/next/src/templates/tip-template.tsx

There were a few things from `create-skill-app` that are out of sync and in an error state. This cleans them out so that ER builds aren't failing.

fix: address lint errors for new ER app

---

apps/epic-react/package.json
apps/epic-react/src/migrations/pt-to-md.ts
pnpm-lock.yaml

I based this off of @vojtaholik's script 🙌 -- https://github.com/skillrecordings/products/blob/main/apps/epic-web/migrations/pt-to-md.ts
All fields that were Portable Text and were switched to Markdown have now been migrated so that the Sanity studio can render those documents.

feat: add script to migrate PT fields to Markdown

---

packages/commerce-server/src/determine-coupon-to-apply.ts
packages/commerce-server/src/format-prices-for-product.test.ts
packages/commerce-server/src/format-prices-for-product.ts

there are many pages where we show pricing for multiple products (e.g.
when there are different tiers) and the coupon coming from a coupon code
is only relevant to one of those products. Ensure that the price gets
calculated correctly for each by restricting the coupon to its product.

feat: exclude coupon if not for productId

---

apps/devrel-fyi/src/pages/index.tsx
apps/epic-react/src/pages/index.tsx
apps/epic-web/src/pages/buy.tsx
apps/epic-web/src/pages/index.tsx
apps/epic-web/src/templates/event-template.tsx
apps/pro-aws/src/pages/index.tsx
packages/skill-api/src/core/services/redeem-golden-ticket.ts
packages/skill-lesson/path-to-purchase/handle-self-redeem.ts
packages/skill-lesson/path-to-purchase/redeem-dialog.tsx
packages/skill-lesson/path-to-purchase/redeem-full-price-coupon.ts
packages/skill-lesson/path-to-purchase/use-coupon.tsx
packages/skill-lesson/team/index.tsx
packages/skill-lesson/team/self-redeem-button.tsx
packages/skill-lesson/video/video-overlays.tsx

The `validateCoupon` function now accepts a `productIds` array for validating coupons that are restricted to a certain product ID (https://github.com/skillrecordings/products/pull/1360). The `redeem-golden-ticket` flow was not passing along a list of product IDs to that function which meant that any coupon restricted to a product ID was coming out as invalid (`coupon-not-valid-for-product`).
This was also going to impact redemption of seats for team/bulk purchases.
More details on this in roam: https://roamresearch.com/#/app/egghead/page/muT11DK4o

fix: pass productIds to validateCoupon

---

apps/testing-javascript/src/components/pricing-section.tsx
apps/testing-javascript/src/pages/index.tsx
packages/skill-lesson/path-to-purchase/redeem-dialog.tsx
packages/skill-lesson/path-to-purchase/use-coupon.tsx

If the coupon is restricted to a specific product, then we need to pass down that product ID as part of the metadata so that the `validateCoupon` check can verify the match. 
Ultimately there is some refactoring that needs to happen in this coupon flow, but for now this is a fix that will re-enable coupons for TJS.

fix: pass in restricted product ID to coupon modal

---

apps/total-typescript/src/pages/buy.tsx
apps/total-typescript/src/templates/home-template.tsx

This is a good temporary fix that follows suit with #1374 and #1373. Once these fixes are in place and we have a little time, a more comprehensive refactoring of this bit of coupon logic is called for.

fix(tt): pass restricted productId to useCoupon

---

packages/skill-api/src/core/services/create-magic-link.ts
packages/skill-api/src/router.ts
packages/skill-api/src/server/send-server-email.ts

This PR adds an internal-use (authenticated against `SKILL_SECRET`) endpoint for requesting a magic link on behalf of a user. It makes use of the existing Verification URL logic that hooks into NextAuth.
Example of calling this `api/skill/create-magic-link` endpoint via a REST client with an `email` param and the `x-skill-secret` header:

feat: add endpoint for requesting user magic link

---

apps/epic-react/src/templates/lesson-template.tsx
apps/epic-react/src/templates/workshop-template.tsx
apps/epic-react/src/utils/lesson-path-builder.ts
packages/skill-lesson/video/collection/index.tsx

This adds an optional `lessonPathBuilder` function to the root `Collection` component so that individual apps can override how those paths are built. This is useful if the path structure of lessons for a specific app differs from the norm. In the case of Epic React v1 we don't use section slugs in the lesson paths. Instead, regardless of whether a lesson is nested in a section or not, we want to render the path as `/workshops/[module-slug]/[lesson-slug]`. This makes overriding the default easy.
This is implemented against https://github.com/skillrecordings/products/pull/1365, but I'm opening as a separate PR to make it easier to review.

feat(er): use custom path builder for lesson list

---

apps/epic-react/src/lib/bonuses.ts
apps/epic-react/src/pages/learn.tsx

@DrShpongle this wires up Epic React bonuses so that they are also loaded based on the purchased `productId`

feat(er): load bonuses based on user's productId

---

apps/epic-react/src/pages/learn.tsx

This tweaks workshop content output so that instead of showing section title and output all section's lessons now we show just link with section title as label that redirects to the first it's lesson (like current EpicReact does)
<details>
</details>
<details>
</details>

refactor(er): tweak Learn page

---

apps/total-typescript/schemas/deskStructure.ts
apps/total-typescript/schemas/documents/chapterResource.tsx
apps/total-typescript/schemas/documents/module.tsx
apps/total-typescript/schemas/index.ts
apps/total-typescript/schemas/structure/chapterResources.js
apps/total-typescript/schemas/structure/chapters.js

this will allow us to preview chapters from the written TT book.

feat(tt): add `chapterResource` document to Sanity schema

---

apps/badass/schemas/documents/article.tsx
apps/badass/src/components/card.tsx
apps/badass/src/components/landing/articles.tsx
apps/badass/src/components/landing/podcasts.tsx
apps/badass/src/components/mdx/components/decorated-list.tsx
apps/badass/src/components/mdx/components/floated-image.tsx
apps/badass/src/components/mdx/components/index.ts
apps/badass/src/components/mdx/index.tsx
apps/badass/src/lib/articles.ts
apps/badass/src/pages/[article].tsx
apps/badass/src/pages/articles.tsx
apps/badass/src/pages/confirm.tsx
apps/badass/src/pages/index.tsx
apps/badass/src/server/og-image.server.tsx
apps/badass/src/styles/mdx-components.css
apps/badass/src/templates/article-template.tsx

This adds `markdownBody` field Article schema (besides some others like `shareCardImage` and `articleHeaderImage`), couple of new mdx components.
Also I've added chatGPT-generated short descriptions for the articles that missed it.
Currently only two articles have been rewritten in mdx:
1. [5 Early Decisions of a Course Business](https://badass-turbo-66t5erj3n-skillrecordings.vercel.app/5-early-decisions-of-a-course-business)
2. [The Process](https://badass-turbo-66t5erj3n-skillrecordings.vercel.app/the-process)
There is some garbage left commented out, I will clean it up after rewrite rest of articles to markdown (and create few more mdx components for that).

feat(badass): markdown for the Articles

---

apps/badass/src/components/card.tsx
apps/badass/src/components/landing/articles.tsx
apps/badass/src/components/mdx/components/accented-title.tsx
apps/badass/src/components/mdx/index.tsx
apps/badass/src/templates/article-template.tsx

This PR add some tweaks for template and mdx components.
Also markdown for the article has got disabled (temporarily) while I'm converting the rest of the articles (to avoid confusing users that might read articles at the moment).

feat(badass): markdown for the Articles (tweaks)

---

packages/database/prisma/schema.prisma

_Note: currently working on setting up a couple pscale deploy requests_
This will help speed up queries that are ordering LessonProgress results
by completedAt date.

feat: add index to LessonProgress.completedAt

---

packages/skill-api/src/core/services/process-stripe-webhook.ts

The `paymentOptions` option is only passed by TJS at this point, so other apps should continue to fallback to `defaultStripe`. This particular instance in `process-stripe-webhook` was being too aggressive in throwing an error.

fix(tt): add missing payment options for TT

---

apps/epic-react/src/@types/mdx-articles.ts
apps/epic-react/src/components/divider.tsx
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/app.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/index.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/initial-data.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/post-class-fix.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/post-class.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/post-default.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/post-ref.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/post-view.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/provider.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/setupTests.js
apps/epic-react/src/components/mdx-components/how-react-uses-closures-to-avoid-bugs/utils.js
apps/epic-react/src/components/mdx-components/index.tsx
apps/epic-react/src/content/articles/how-react-uses-closures-to-avoid-bugs.mdx
apps/epic-react/src/pages/[article].tsx
apps/epic-react/src/pages/articles.tsx
apps/epic-react/src/styles/globals.css
apps/epic-react/src/templates/article-template.tsx

This adds minimal styles to the articles index, adds `YOU MIGHT ALSO LIKE` component (the list of  other articles) and one MDX component that is used in one of the articles.
<details>
<summary>Articles</summary>
</details>
<details>
<summary>Article</summary>
</details>

feat(er-next): adjust articles index and article template

---

apps/total-typescript/src/lib/exercises.ts
packages/skill-lesson/schemas/exercise.ts
packages/skill-lesson/schemas/solution.ts

The #1365 PR wasn't omitting `_id` for lesson solutions in TT. That resulted in a Zod parse error. This fixes that.

fix(tt): solution objects don't have an _id

---

apps/epic-web/src/trpc/routers/bonuses.ts

Users weren't allowed to claim the Testing JavaScript bonus seat. We had a value in the query that doesn't exist on our database. 
I tested this locally and claimed a seat correctly.

fix(ew): deleting wrong value to claim a bonus seat 

---

apps/testing-javascript/src/components/landing/access-your-course.tsx
apps/testing-javascript/src/pages/api/skill/[...skillRecordings].ts
apps/testing-javascript/src/templates/lesson-template.tsx

This does two things:
1. Allows last lesson in the module to get completed
2. Fixes the `courseCompleted` calculation function so that "Download Certificate" appears after all lesson get completed now.
About the person who reported about this issue - I think we should let him know he needs to rewatch last lessons in each of the modules to get them completed and get certificate download link eventually

fix(TJS-61): testing javascript course completion certificate

---

packages/skill-api/src/core/services/process-stripe-webhook.ts

Previously we were comparing two emails that were always identical
because the user tied to the Merchant Customer record had already been
updated. Because of this, an email was never getting sent to the new
user.

feat: compare previous email on customer updated

---

packages/skill-api/src/core/services/process-stripe-webhook.ts
packages/skill-api/src/server/send-server-email.ts

Trying to understand what exactly the error is that is resulting in 500 errors for `api/skill/webhook/stripe-internal`.

feat(tjs): add logging for 500 error

---

apps/testing-javascript/src/styles/team.css

styles(tjs): re-styling the Invite Team widget

---

apps/testing-javascript/src/components/landing/interviews.tsx

we aren't supporting downloads of video content for TJS at this time and
that link wasn't downloading the right thing anyway.

feat(tjs): remove download interviews link

---

apps/total-typescript/src/exercise/stackblitz-iframe.test.ts
apps/total-typescript/src/exercise/stackblitz-iframe.tsx

Fixes a bug in https://totaltypescript.com/tutorials/solving-typescript-errors/errors/fixing-cannot-redeclare-block-scoped-variable/exercise

Fixed bug where exercises in folders did not trigger a start command

---

apps/colt-steele/src/pages/api/skill/[...skillRecordings].ts
apps/devrel-fyi/src/pages/api/skill/[...skillRecordings].ts
apps/devrel-fyi/src/pages/thanks/purchase.tsx
apps/epic-react/src/pages/api/skill/[...skillRecordings].ts
apps/epic-react/src/pages/thanks/purchase.tsx
apps/pro-aws/src/pages/api/skill/[...skillRecordings].ts
apps/pro-aws/src/pages/thanks/purchase.tsx
apps/pro-nextjs/src/pages/api/skill/[...skillRecordings].ts
packages/create-skill-app/templates/next/src/pages/api/skill/[...skillRecordings].ts
packages/create-skill-app/templates/next/src/pages/thanks/purchase.tsx

- **feat(er): use PaymentOptions for Stripe provider**
- **feat: use PaymentOptions in remaining apps**

sks 92 (and sks 89) set up payment options for epic react and other remaining apps

---

apps/total-typescript/package.json
apps/total-typescript/seed_data/data.Products.essentials-workshop.00001.sql
apps/total-typescript/src/inngest/functions/sanity/product/index.ts
apps/total-typescript/src/inngest/functions/sanity/product/sanity-product-created.ts
apps/total-typescript/src/inngest/functions/sanity/product/sanity-product-deleted.ts
apps/total-typescript/src/inngest/functions/sanity/product/sanity-product-updated.ts
apps/total-typescript/src/inngest/functions/sanity/sanity-inngest-events.ts
apps/total-typescript/src/inngest/inngest-config.ts
apps/total-typescript/src/inngest/inngest.server.ts

This incorporates the automation from Epic Web to create, update, and delete products in Sanity. These operations are then reflected in both our database and Stripe.

feat(tt): add automation via inngest to create a product in sanity + db + stripe

---

packages/skill-lesson/path-to-purchase/pricing.tsx

attn @kentcdodds
—
Fix plural typo when only 1 quantity is present
I couldn't manage to spin up the repo locally even after installing all the deps, but here is a proof of concept:

[epic-web] Pluralize "spot" string for `availability?.quantityAvailable`

---

apps/epic-web/src/components/app/navigation.tsx
apps/epic-web/src/pages/events/index.tsx

> [!IMPORTANT]  
> This PR was opened in response to commits [2d1e497](https://github.com/skillrecordings/products/commit/2d1e497ad88b2199d7fb3492b0c301a2b11cee30) and [44c83b6](https://github.com/skillrecordings/products/commit/44c83b6277791633c944514a0638b78c7901fa44), following my effort in https://github.com/skillrecordings/products/pull/1509.
>
> **`apps/epic-web/src/components/app/navigation.tsx`** :: 🛠️ Improvement
> Moves the quantity into the JS expression to remove redundancy
>
> **`apps/epic-web/src/pages/events/index.tsx`** :: 🐞 Bug fix
> The current implementation will show `<Spinner /> spots left` when `availability?.quantityAvailable` is falsy, rather than only the spinner.
attn @kentcdodds @vojtaholik @Creeland
—
* Fix plural typo when only 1 quantity is present
* Improve …

Dynamically pluralize "spot" string instances

---

apps/epic-react/src/lib/bonuses.ts
apps/epic-react/src/lib/workshops.ts
apps/epic-react/src/pages/learn.tsx
apps/epic-react/src/pages/modules/[module]/[lesson]/index.tsx

there is no `sectionSlug` in the URL path params, so we were always getting `null` when trying to look up the `section`.
this adds a reverse lookup of the `section` based on the lesson's slug and the list of `resources` on the `module`

feat(tt): look up section slug for module/lesson

---

apps/epic-react/src/components/app/navigation/feedback-button.tsx
apps/epic-react/src/components/app/navigation/index.tsx
apps/epic-react/src/components/app/navigation/logout-button.tsx
apps/epic-react/src/components/app/navigation/mobile-navigation.tsx
apps/epic-react/src/components/app/navigation/theme-toggle.tsx
apps/epic-react/src/components/feedback-widget/feedback-dialog.tsx
apps/epic-react/src/middleware.ts
apps/epic-react/src/server/get-middleware-response.ts

This PR implements the following:
- `Modules` menu item is now visible for non-logged / non-registered users, they can navigate to the `/learn` page now.
- Logged in pro users get redirected from `/` to `/learn`, non-logged in users stay on `/` landing page
- Logged in users once they try to naviagate to `/login` get redirected to `/learn`
- Mobile menu gets closed after user clicks on any item in it
<details>
<summary>**Modules** menu item for non-logged in users:</summary>
</details>
<details>
<summary>Mobile menu gets closed after user clicks on any item in it</summary>
</details>

feat(er-next): rework navigation menu

---

apps/epic-react/seed_data/data.Products.upgrades.00001.sql

Run these against your local `kcd-products` database to have Upgradable Products enabled for ERv1. We will also need to run these against production database before going live.

feat: add UpgradableProducts seed data for ERv1

---

packages/database/prisma/schema.prisma

Adding UserPrefs table to store user preferences.
---
Once you pull these changes down locally, you'll need to do the following:
`pnpm -w generate` to regenerate the Prisma schema with this change.
`pnpm db:push` from any app whose local DB is running to update the schema

feat(db): add user prefs table

---

apps/epic-react/src/inngest/functions/purchase/purchase-transfer-complete.ts
apps/epic-react/src/inngest/functions/sanity/product/index.ts
apps/epic-react/src/inngest/functions/sanity/product/sanity-product-created.ts
apps/epic-react/src/inngest/functions/sanity/product/sanity-product-deleted.ts
apps/epic-react/src/inngest/functions/sanity/product/sanity-product-updated.ts
apps/epic-react/src/inngest/functions/sanity/sanity-inngest-events.ts
apps/epic-react/src/inngest/inngest.config.ts
apps/epic-react/src/inngest/inngest.server.ts

This adds more inngest functions:
- purchaseTransferComplete
- sanityProductCreated
- sanityProductUpdated
- sanityProductDeleted
We are still getting a `404` on `/thanks/purchase` which looks like a mismatch on the product id (need to investigate more) but this would allow for sanity product id to stay in sync with the database.
I've left these functions out for now as they don't seem relevant to epic react v1:
- processNewTip
- addSrtToMuxAsset
- lessonCompleted
- writeAnEmail
functions commented out:
- inactivityAfterPurchase
- resumeProgressAfterInactivity

epic react next: add rest of er inngest functions

---

packages/skill-lesson/markdown/serialize-mdx.ts
packages/skill-lesson/markdown/shiki-twoslash-plugin.ts
packages/skill-lesson/package.json
pnpm-lock.yaml

This PR:
- Removes the dependency on shiki-service
- Moves all shiki-twoslash rendering to the build script/rebuild script
If this works, we can close shiki-service for good - and good riddance.
The reason we had shiki-service in the first place was to solve a problem: by default, twoslash looks at the file system to acquire its types. So, `typescript`, `@types/react` etc all need to be _on the file system_ when twoslash transforms the code. This was not a problem on initial build, but on subsequent builds (due to a Sanity update) the incremental rebuild didn't have the entire FS loaded.
shiki-service was built as a persistent server so that this file system would always be in place.
This PR makes it so that twoslash looks to a CDN for all of its types, including TS. This means it can run …

Added automatic type acquisition to shiki plugin

---

.gitignore
apps/total-typescript/package.json
packages/skill-lesson/markdown/serialize-mdx.ts
packages/skill-lesson/markdown/shiki-twoslash-plugin.ts
packages/skill-lesson/package.json
packages/skill-lesson/tsconfig.json
pnpm-lock.yaml

This PR:
Removes the dependency on shiki-service
Moves all shiki-twoslash rendering to the build script/rebuild script
If this works, we can close shiki-service for good - and good riddance.
The reason we had shiki-service in the first place was to solve a problem: by default, twoslash looks at the file system to acquire its types. So, typescript, @types/react etc all need to be on the file system when twoslash transforms the code. This was not a problem on initial build, but on subsequent builds (due to a Sanity update) the incremental rebuild didn't have the entire FS loaded.
shiki-service was built as a persistent server so that this file system would always be in place.
This PR makes it so that twoslash looks to a CDN for all of its types, including TS. This means it can run on …

Added Automatic Type Acquisition To Shiki Twoslash

---

packages/skill-lesson/markdown/shiki-twoslash-plugin.ts

Before this change, shiki was too eager to interpret a code snippet as 'lang: typescript' if a lang was not found, leading to dodgy syntax highlighting on code snippets intended to be `txt`:
Now, it'll interpret snippets without a lang as `txt` instead of `typescript`.

Fixed the default lang on shiki

---

apps/epic-web/package.json
apps/epic-web/schemas/documents/product.tsx
apps/epic-web/src/inngest/functions/sanity/product/sanity-product-created.ts
apps/total-typescript/schemas/documents/product.tsx
apps/total-typescript/src/inngest/functions/sanity/product/sanity-product-created.ts
packages/convertkit-sdk/src/convertkit.ts
packages/skill-api/src/core/services/convertkit/convertkit-tag-purchase.ts
pnpm-lock.yaml

- the reason why the property of "purchase on" wasn't being set in CK was an issue with the format
- CK wasn't tagging users properly because the tag_id wasn't being pass in sanity
- added the creation of the tag in the automation once we create a product ins sanity

feat: add automation to create a purchased tag in ck when a product is created

---

packages/commerce-server/src/format-prices-for-product.ts
packages/database/src/prisma-api.ts
packages/skill-lesson/trpc/routers/pricing.ts

There were two issues with this flow:
1. the second upgrade (Standard->Pro) was failing because we weren't
finding the right `UpgradableProducts` record. We now filter out the
`Basic->Pro` one since you've already done a `Basic->*` upgrade. That
leaves only the `Standard->Pro` upgrade path.
2. the base prices of both the Basic and Standard purchases were being
used to determine the fixed discount of the `Standard->Pro` upgrade
which resulted in too much money being discounted from the price. We
now filter out the `Basic` purchase since that was upgraded to
`Standard` and just use the base price of the `Standard` purchase.

feat(er): fix Basic->Standard->Pro upgrade chain

---

apps/epic-react/src/templates/lesson-template.tsx

**for a user who hasn't purchased yet, no button**
**for a user who has purchased, show button**

feat(er): render Completion button for purchasers

---

apps/epic-react/src/components/lesson-completion-toggle.tsx

removes navigation on lesson completion as we figure out busted "get next lesson" functionality.
Currently `moduleProgress` is setting the first lesson it finds in a module as the next lesson which is unexpected behavior if you skipped a couple lesson or don't want to watch a welcome video

fix(ER): remove navigating on lesson completion

---

.github/workflows/main.yml
apps/total-typescript/src/exercise/stackblitz-iframe.test.ts
apps/total-typescript/src/exercise/stackblitz-iframe.tsx

[Decision Doc](https://gist.github.com/mattpocock/106e31b6c462344219d484bfc29fc38e)
Ended up going with solution 3. Working nicely.
To test, visit the [branch's version](https://total-typescript-turbo-a250xm5ym-skillrecordings.vercel.app/workshops/typescript-pro-essentials/mutability/fixing-a-type-assignment-inference-error/exercise) of Pro Essentials, then [our live one](https://www.totaltypescript.com/workshops/typescript-pro-essentials/mutability/fixing-a-type-assignment-inference-error/exercise) to see the difference.

Fixed Stackblitz in pro essentials workshop

---

apps/total-typescript/src/components/book/book-exercise-embed.tsx

On the off chance there is a typo or other failure to load exercise data for a chapter exercise we don't want to show broken UI that leads to a 404.

fix(tt): protect agains typos in sanity

---

apps/epic-react/src/data/coupon-import.ts

This script has already been run to restore some missing coupons to the production database for ER. I'm committing the script because it is a useful artifact (for example, because we kept similar import scripts, I was able to produce this one in ~15 minutes by reusing and modifying an existing script that we kept in the repo).

feat(er): import missing ER coupon records

---

apps/total-typescript/src/components/book/primary-chapter-toc.tsx
apps/total-typescript/src/components/book/secondary-chapter-toc.tsx

Before:
After:
URL:
/books/total-typescript-essentials/deriving-types

Made children of 'exercises' not show up in book ToC

---

apps/epic-react/src/lib/articles.ts
apps/epic-react/src/pages/articles.tsx

This adds `revalidate` to the `getStaticProps` functions on the `/articles` page so that new published articles appear without redeploy.
Also sorting articles by date applied.

fix(ER-next): ISG for /articles + sort by date

---

apps/epic-react/src/pages/transfer/[purchaseUserTransferId].tsx

The _Accept Purchase Transfer_ page was missing from ERv1. This PR fixes that.

feat(er): add missing Purchase Transfer page

---

packages/commerce-server/src/props-for-commerce.ts

The legacy Epic React site accepted 'golden ticket' coupon code via the
`coupon` query param. We now use the `code` query param. Since we've
distributed a bunch of coupon URLs with the `coupon` query param, this
updates the commerce props logic to work with both.

feat(er): use `code` or `coupon` query param

---

apps/epic-react/src/pages/modules/[module]/completed.tsx

[linear](https://linear.app/skillrecordings/issue/ER-121/incorrect-link-to-the-next-module-on-the-module-completed-page)
<details>
</details>
<details>
</details>

fix(er-next): sort the modules array to get proper next module link on /completed page

---

apps/epic-react/src/lib/workshops.ts
apps/epic-react/src/pages/modules/[module]/[lesson]/index.tsx
apps/epic-react/src/pages/modules/[module]/[lesson]/solution/index.tsx

If someone mistakenly navigates to a `/modules/:module-slug/:lesson-slug` url where the `lesson-slug` is correct but the module the `module-slug` is non-existent (e.g. url should have been `/tutorials/` and not `/modules/`), the lesson page will through a `500` instead of a `404` because we try to fetch the module with `getWorkshop` and zod errors out. This returns a `404` instead

fix(er): properly 404 on wrong lesson urls

---

apps/epic-react/src/components/lesson-completion-toggle.tsx
apps/epic-react/src/components/video-overlays/finished-section-overlay.tsx
apps/epic-react/src/components/video-overlays/lesson-complete-overlay.tsx
packages/skill-lesson/lib/module-progress.ts
packages/skill-lesson/lib/modules.ts
packages/skill-lesson/video/module-progress.tsx

We had hard-coded values in the `Complete and Continue` button that navigated to the next lesson when you are in a `module` lesson.
This needs to be dynamic now that we have tutorials on epic react (and in the future when we implement /workshops though I'd advocate to ditch this button in favor of how skill-stack currently handles things)
When we remove sections from url we will need to update this functionality again as `section.slug` is hardcoded in the url that is navigated to. 
https://www.loom.com/share/ec43f53ce0584854bb4e92d36483a6e9
Also fixed icon styling on the complete and continue overlay

fix(er) fix broken complete and continue button for tutorials

---

apps/epic-react/src/components/lesson-completion-toggle.tsx
apps/epic-react/src/components/video-overlays/lesson-complete-overlay.tsx

fix(er): apply styles for complete and continue button in light mode

---

apps/epic-react/src/components/exercise-overlay.tsx
apps/epic-react/src/pages/workshops/[module]/[lesson]/index.tsx
apps/epic-react/src/pages/workshops/[module]/[lesson]/solution/index.tsx
apps/epic-react/src/pages/workshops/[module]/index.tsx
apps/epic-react/src/styles/globals.css
apps/epic-react/src/templates/exercise-template.tsx
apps/epic-react/src/trpc/routers/module-resources.ts
packages/skill-lesson/hooks/use-mux-player.tsx
packages/skill-lesson/hooks/use-next-lesson.ts
packages/skill-lesson/lib/modules.ts
packages/skill-lesson/trpc/routers/lessons.ts
packages/skill-lesson/video/collection/index.tsx

With the changes made in this PR https://github.com/skillrecordings/products/pull/1691 we broke the tutorials since the also use `exercise-template` 
- this fixes the tutorials 404 
- includes the stand alone lessons in the `LessonList` component and style them 
- fixes the `nextLesson` query

fix(er): fix nextLesson and addModuleWithResources for stand alone  lessons 

---

apps/epic-react/src/components/pricing-section.tsx
apps/epic-react/src/pages/buy.tsx
apps/epic-react/src/pages/index.tsx
apps/epic-react/src/trpc/routers/cta.ts
packages/skill-lesson/path-to-purchase/product-tiers.tsx

the query param coupon code wasn't properly being passed down and the epic react grid didn't have a countdown renderer on the buy page

fix: allow a countdown to appear for an expiring query coupon

---

apps/epic-react/src/pages/api/discord.tsx

This way people skip the onboarding process
This will require an environment variable for `DISCORD_MEMBER_ROLE_ID` which should be set to `715223877386502224`

feat(discord): add member role for epic react connection

---

apps/epic-web/src/components/calculations/calculate-splits.ts
apps/epic-web/src/components/calculations/calculate-totals.ts
apps/epic-web/src/inngest/functions/stripe/slack-daily-reporter.ts
apps/epic-web/src/inngest/functions/stripe/slack-monthly-reporter.ts
apps/epic-web/src/lib/transactions.ts

nicoll/include balance transactions for reports 

---

apps/total-typescript/src/pages/survey.tsx

If they have a ck cookie, we can record each answer individually instead of waiting until the last question.

feat(tt): record individual survey answers

---

apps/epic-web/src/inngest/functions/stripe/slack-daily-reporter.ts
apps/epic-web/src/inngest/functions/stripe/slack-weekly-reporter.ts

chore(ew): update channels where to send the report

---

apps/epic-react/src/components/exercise-overlay.tsx
apps/epic-react/src/components/landing/intro-tour-video.tsx
apps/epic-react/src/pages/get-started/index.tsx
apps/epic-react/src/templates/embed-template.tsx
apps/epic-react/src/templates/purchased-product-template.tsx
apps/epic-react/src/templates/tip-template.tsx
apps/epic-web/src/components/exercise-overlay.tsx
apps/epic-web/src/pages/conf/2024/[speaker].tsx
apps/epic-web/src/pages/conf/2025/index.tsx
apps/epic-web/src/pages/full-stack/index.tsx
apps/epic-web/src/pages/get-started/index.tsx
apps/epic-web/src/pages/testing/index.tsx
apps/epic-web/src/templates/embed-template.tsx
apps/epic-web/src/templates/purchased-event-template.tsx
apps/epic-web/src/templates/purchased-product-template.tsx
apps/epic-web/src/templates/talk-template.tsx
apps/epic-web/src/templates/tip-template.tsx
apps/testing-javascript/src/components/landing/access-your-course.tsx
apps/testing-javascript/src/components/playlist/playlist-item.tsx
apps/testing-javascript/src/templates/landing-template.tsx
apps/total-typescript/src/app/_components/video-player.tsx
apps/total-typescript/src/pages/welcome/index.tsx
apps/total-typescript/src/templates/tip-template.tsx
packages/create-skill-app/templates/next/src/templates/embed-template.tsx
packages/create-skill-app/templates/next/src/templates/purchased-product-template.tsx
packages/create-skill-app/templates/next/src/templates/tip-template.tsx
packages/skill-lesson/markdown/mdx-components.tsx
packages/skill-lesson/video/video.tsx

adds metadata to mux player instances

feat: add post metadata to mux player

---

apps/epic-web/src/principles/data.json

Not sure how we missed these, but here they are now.

add missing epic programming principles

---

apps/total-typescript/schemas/documents/article.tsx
apps/total-typescript/src/lib/articles.ts
apps/total-typescript/src/pages/[article].tsx
apps/total-typescript/src/templates/article-template.tsx

Matt mentioned putting up a 'email wall' for the cursor rules article for the sale that we will be running. 
This adds a `withEmailWall` property to articles in sanity that we can flip on if we want to selectively show this CTA to people. Makes sense to me to turn this login wall off after the sale is over.

feat: add sanity-powered login wall for articles
