skillrecordings/products

README.md
=> update template app start command in readme

.github/workflows/integration.yml, .kodiak.toml, README.md, package.json
=> attempt to use cypress for testing automations

apps/next-product-starter/src/components/color-mode-toggle.tsx
=> starter: correctly resolve system color mode

packages/time/src/__tests__/time.test.ts, packages/time/src/index.ts
(#19) bunch of unit tests for the functions in the time package
=> unit tests for functions in time package

.gitignore, README.md, apps/rustadventure/package.json, apps/rustadventure/src/components/forms/convertkit/index.tsx, apps/rustadventure/src/pages/api/convertkit/subscribe.ts, apps/rustadventure/src/pages/index.tsx
=> add endpoint for rustadventure subscribers

apps/compilersforhumans/src/pages/index.tsx, apps/engmanagement/src/pages/index.tsx, apps/keyboardlegend/src/pages/index.tsx, packages/convertkit/src/forms/index.tsx
=> subscribe form: separate styles

README.md, apps/engmanagement/package.json, package.json, pnpm-lock.yaml
- Add `postbuild` to `turbo run build` tasks so that it turbo is able to properly cache it
=> Make sure postbuild is run

package.json
Add a quick rm -rf of relevant dist, .next, .turbo folders to help simulate builds from fresh filesystems locally
=> Add a clean up npm script

packages/player/src/components/hls-source.tsx, packages/player/src/components/video.tsx
=> more robust hls

packages/player/src/components/hls-source.tsx, packages/player/src/components/video.tsx, packages/player/src/context/video-context.tsx
=> monitor ios fullscreen state and send pause on exit since the video pauses but does not send an event

apps/next-product-starter/src/pages/player.tsx, packages/player/src/hooks/use-notes-cues.ts, packages/player/src/machines/video-machine.ts, packages/player/src/selectors/index.ts
=> handle changing videos with the player

packages/config/src/index.ts, packages/convertkit/package.json, packages/convertkit/src/api/subscribe.ts, packages/convertkit/src/forms/index.tsx, packages/convertkit/src/forms/subscribe/README.md, packages/convertkit/src/forms/subscribe/index.tsx, packages/react/package.json, pnpm-lock.yaml
Form component that takes first name and email address and subscribes to either a form, tag, or sequence in ConvertKit using `/api/convertkit/subscribe` endpoint.
=> shared `<SubscribeForm />` component

apps/escuelafrontend/src/components/app/header.tsx
| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/25487857/133992007-42e9c781-6ca5-4eea-b9d7-7ba48f258388.gif" width="250" alt="before">  | <img src="https://user-images.githubusercontent.com/25487857/133992085-146fd48a-da4e-4818-b0f8-1466e466cfdf.gif" width="250" alt="after">  |
=> escuelafrontend: close mobile nav on page change

apps/engmanagement/src/pages/[slug].tsx, packages/config/src/index.ts, packages/convertkit/src/api/subscribe.ts, packages/convertkit/src/forms/subscribe/index.tsx, packages/convertkit/src/forms/subscribe/subscribe-to-convertkit-form.tsx
=> subscribe form tweaks

apps/kcdbundle/src/components/content/homepage.mdx, apps/kcdbundle/src/pages/index.tsx
I don't have the monorepo running locally yet, so I'm dependent on a staging build to see the results, but given the level of simplicity in these changes...
=> Updates copy and order of products on KCD bundle site

apps/compilersforhumans/src/pages/answer.tsx
Update quiz question with better example
=> Update c4h quiz with better question example

apps/compilersforhumans/src/config.js, apps/compilersforhumans/src/pages/answer.tsx
=> Update c4h names everywhere but the homepage

apps/cssdestructured/src/pages/confirmed.mdx, apps/cssdestructured/src/pages/index.tsx
* Redirect form to confirmed page
* Update copy
=> Redirect CSS Destructured form to confirmed

apps/cssdestructured/src/pages/answer.tsx, apps/cssdestructured/studio/schemas/code-file.js, apps/cssdestructured/studio/schemas/questions/code.js, apps/cssdestructured/studio/schemas/questions/essay.js, apps/cssdestructured/studio/schemas/questions/multiple-choice.js, apps/cssdestructured/studio/schemas/questions/multiple-image-choice.js, apps/cssdestructured/studio/schemas/quiz.js, apps/cssdestructured/studio/schemas/schema.js, packages/quiz/package.json, packages/quiz/src/components/question-to-show.tsx, packages/quiz/src/components/question/code.tsx, packages/quiz/src/components/question/index.tsx, packages/quiz/src/styles/index.css, packages/types/src/index.ts, pnpm-lock.yaml
This is using [sanspack-react](https://www.npmjs.com/package/@codesandbox/sandpack-react) package which gives us an editor and handles generating of sandbox url that we can then submit.
[Example URL](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKCA7AJjAHgOgBYAuAtlEqAMYD2qBMNSIAPAK5QAE5UAhnHALwAdEFAhwCQgHwDUbNoxETGXDt16CQeSkRhC2eAE4ww6gPSSAElpiMTXRSYXTZ8iIuWce_IVwBGlZuIgeobGQrZ-AZIAghEENnY2jjJyCkoqnupUNFzkgcFGplkEOYESAMLUxbnx9kk2rFKo0gCSbMwADuhctOhsBHiibGD6Wn14MGwAjswQAF4AhCAANCCiAEJoXPoAnkhgXFBwMAC-K2LbsHA45LxkIEV0BAw4ImJswE5srwQAtOewPwI23aMEQbFQ1BgAG5PuhRO1uNswWBYFgYahjtJpCJ3p8iFsAOZoH5oESoGA_OjoMEADnaaOkmKaqHwVlxySoUEo-jBPm45AA1ujZGBKj99kRoEi2AByKL6CAHGVLNhwLioOB_GAKsDCvrYX6YKj6boQahgiHk9FM6Ss7SITQAN217NktCwhpgxtN5raGG1ZOhjKxLN8_gIro4lC5PLYfJyQs-opo4q4kqg0rlC …
=> quiz: code question type

apps/cssdestructured/src/pages/index.tsx
First pass at a CSS Destructured headline and Email course CTA.
=> Update CSS Destructured headline and add email course CTA

apps/kcdbundle/src/pages/api/users/index.ts, apps/kcdbundle/src/pages/buy/email.tsx, apps/kcdbundle/src/utils/sessions.ts, packages/convertkit/src/api/subscriber.ts, packages/convertkit/src/utils/fetch-convertkit-subscriber.ts
=> finalizing the kcdbundle for launch

packages/player/package.json, packages/player/src/components/code-block.tsx, packages/player/src/components/cue-bar.tsx, packages/player/src/components/progress-bar.tsx, pnpm-lock.yaml
Reduced CodeBlock dependency for the Player package
=> CodeBlock for Player package

apps/next-product-starter/src/pages/player.tsx, packages/player/src/actions/index.ts, packages/player/src/components/video.tsx, packages/player/src/context/video-context.tsx, packages/player/src/machines/video-machine.ts
I didn't test this, but the principle is sound 🤡
=> add an end event handler that we can override

apps/next-product-starter/src/pages/player.tsx, packages/player/src/components/control-bar.tsx, packages/player/src/components/cue-bar.tsx, packages/player/src/components/player.tsx, packages/player/src/styles/scss/components/control-bar.scss, packages/player/src/styles/scss/components/cue-bar.scss, packages/player/src/styles/scss/components/side-panel.scss, packages/player/src/styles/scss/components/slider.scss, packages/player/src/styles/scss/components/time.scss, packages/player/src/styles/scss/components/volume.scss, packages/player/src/styles/scss/miscellaneous.scss
- reworked cue notes
- tweaked control bar
next steps:
- add author information to the incoming vtt
- adjust cue popups
=> Next portion of Player improvements

apps/next-product-starter/src/pages/player.tsx
- cue notes interact with sidebar now
- fixed scroll
=> Cue Notes tweaks

apps/next-product-starter/src/pages/player.tsx, packages/player/src/components/control-bar.tsx, packages/player/src/components/cue-bar.tsx, packages/player/src/components/player.tsx, packages/player/src/styles/scss/components/control-bar.scss, packages/player/src/styles/scss/components/control.scss, packages/player/src/styles/scss/components/cue-bar.scss, packages/player/src/styles/scss/components/menu/menu-popup.scss, packages/player/src/styles/scss/components/progress-bar.scss, packages/player/src/styles/scss/components/progress.scss, packages/player/src/styles/scss/components/slider.scss, packages/player/src/styles/scss/components/volume.scss, packages/player/src/styles/scss/mixins.scss, packages/player/src/styles/scss/variables.scss
https://user-images.githubusercontent.com/25487857/149170922-c44512df-905d-486f-be75-66facd46e140.mp4
=> player: display note avatars + UI adjustments

apps/engmanagement/src/pages/confirm.tsx, apps/engmanagement/src/pages/index.tsx
subscribers get sent to https://www.engmanagement.dev/the-value-of-values
=> EM: free chapter CTA

apps/engmanagement/src/pages/[slug].tsx, apps/engmanagement/src/utils/check-subscriber.ts
=> check query param for ck id as well as cookie with no asymc

packages/player/src/hooks/use-player-prefs.ts, packages/player/src/utils/cookies.ts
Transferred `usePlayerPrefs` hook from `egghead-next`
=> usePlayerPrefs hook

packages/player/src/actions/index.ts, packages/player/src/components/control-bar.tsx, packages/player/src/components/controls/closed-captions-menu-button-control.tsx, packages/player/src/components/menu/menu-button.tsx, packages/player/src/hooks/use-subtitles-track-list.ts, packages/player/src/machines/video-machine.ts
=> player: closed captions controls

apps/next-product-starter/src/pages/video/[slug].tsx, packages/player/package.json, packages/player/src/components/control-bar.tsx, packages/player/src/components/controls/play-toggle-control.tsx, packages/player/src/components/cue-bar.tsx, packages/player/src/components/player.tsx, packages/player/src/machines/video-machine.ts, packages/player/src/selectors/index.ts, packages/player/src/styles/scss/components/play-pause.scss, pnpm-lock.yaml
this implements loading of video resource in a way that enables for better integration (not only) on egghead.io.
=> player(feat): implement loadResource service

apps/next-product-starter/src/components/layout.tsx, apps/next-product-starter/src/pages/answer.tsx, apps/next-product-starter/src/pages/buy.tsx, apps/next-product-starter/src/pages/confirm.mdx, apps/next-product-starter/src/pages/confirmed.mdx, apps/next-product-starter/src/pages/excited.mdx, apps/next-product-starter/src/pages/index.tsx, apps/next-product-starter/src/pages/invoice.tsx, apps/next-product-starter/src/pages/learn.tsx, apps/next-product-starter/src/pages/login.tsx, apps/next-product-starter/src/pages/redirect.tsx, apps/next-product-starter/src/pages/thanks.tsx, apps/next-product-starter/src/pages/unsubscribed.mdx, apps/next-product-starter/src/templates/article.tsx
It was "whack-a-mole" with the default default title so this localizes it at the app level a little more.
=> feat(next-product-starter): use local layout to capture better meta

apps/typescriptcourse/src/templates/email-course.tsx
This makes a minor copy change from web3 to webdev for Joe Previte's about me.
(I kinda stopped writing about web3 so removed from Twitter bio and here).
=> chore(TS course): update joe's about me

packages/player/package.json, packages/player/src/components/shortcut.tsx
=> fix(player): restrict keyboard shortcuts to certain elements only 

apps/testingaccessibility/src/pages/confirmed.tsx, apps/testingaccessibility/src/pages/role.tsx
* Removes technicality from job role options for TA survey
=> Update TA Job Role button to "Something Else"

apps/typescriptcourse/src/pages/index.mdx
=> feat(typescriptcourse): swap out the form number to use all module form

apps/testingaccessibility/src/pages/accessibility-reviews/index.tsx, apps/testingaccessibility/src/pages/workshops/index.tsx, apps/testingaccessibility/studio/config/.checksums, apps/testingaccessibility/studio/config/@sanity/vision.json, apps/testingaccessibility/studio/package.json, apps/testingaccessibility/studio/sanity.json, apps/testingaccessibility/studio/schemas/documents/review.js, apps/testingaccessibility/studio/schemas/documents/workshop.js, apps/testingaccessibility/studio/yarn.lock
=> feat(testingaccessibility): order sanity documents

apps/testingaccessibility/README.md, apps/testingaccessibility/src/pages/_app.tsx
=> fix(testingaccessibility): theme error

apps/testingaccessibility/prisma/schema.prisma, apps/testingaccessibility/src/lib/prisma-api.ts, apps/testingaccessibility/src/pages/api/progress/index.ts, apps/testingaccessibility/src/pages/api/progress/lessons/[slug].ts
=> refactor progress to prisma

apps/testingaccessibility/src/components/portable-text/index.tsx, apps/testingaccessibility/studio/package.json, apps/testingaccessibility/studio/sanity.json, apps/testingaccessibility/studio/schemas/objects/bodyImage.js, apps/testingaccessibility/studio/yarn.lock
this makes it easier to browse cloudinary assets as well as get additional image metadata such as dimensions that can be used on the frontend.
=> update(testingaccessibility): use cloudinary plugin for sanity

apps/testingaccessibility/process.d.ts, apps/testingaccessibility/src/pages/api/sanity/webhooks/add-all-records-to-algolia.ts, apps/testingaccessibility/src/pages/api/sanity/webhooks/add-records-to-algolia.ts, apps/testingaccessibility/src/utils/algolia/sanity-algolia-client.ts, apps/testingaccessibility/src/utils/sanity-client.ts
=> fix(testingaccessibility): catch errors and use webhook secret

apps/testingaccessibility/next.config.js, apps/testingaccessibility/src/components/search/autocomplete.tsx, apps/testingaccessibility/src/pages/invoices/index.tsx, apps/testingaccessibility/src/pages/learn/[module]/[section]/[lesson]/index.tsx, apps/testingaccessibility/src/pages/learn/index.tsx, apps/testingaccessibility/src/templates/lesson-template.tsx, apps/testingaccessibility/src/templates/module-template.tsx, apps/testingaccessibility/src/templates/section-template.tsx, apps/testingaccessibility/src/utils/progress.ts
=> update(testingaccessibility): templates

apps/testingaccessibility/src/utils/get-resource-paths.test.ts
=> test(testingaccessibility): getResourcePaths utils

apps/testingaccessibility/package.json, apps/testingaccessibility/src/utils/progress.test.ts, pnpm-lock.yaml
=> test(testingaccessibility): getProgress utils

apps/kcdbundle/src/pages/index.tsx
=> update(kcdbundle): revert to default share card

apps/testingaccessibility/src/pages/api/auth/[...nextauth].ts, apps/testingaccessibility/src/pages/learn/_middleware.ts, apps/testingaccessibility/src/server/get-purchased-product.ts
=> feat(testingaccessibility): purchases added to session token

apps/testingaccessibility/src/lib/prisma-api.ts, apps/testingaccessibility/src/pages/learn/index.tsx, apps/testingaccessibility/src/server/ability.ts
=> feat(testingaccessibility): use casl for specific product

apps/testingaccessibility/src/components/app/navigation.tsx, apps/testingaccessibility/src/context/user-context.tsx, apps/testingaccessibility/src/pages/_app.tsx, apps/testingaccessibility/src/server/ability.ts
=> feat(testingaccessibility): make the token available in user context

apps/advanced-typescript/next.config.js, apps/advanced-typescript/package.json, apps/advanced-typescript/src/pages/index.tsx, pnpm-lock.yaml
=> og headers on advanced typescript and removed trailer

apps/typescriptcourse/src/components/footer.tsx, apps/typescriptcourse/src/pages/build-a-typescript-project-from-scratch.mdx, apps/typescriptcourse/src/pages/index.mdx, apps/typescriptcourse/src/pages/navigate-a-typescript-codebase.mdx
=> feat(typescriptcourse): landing page for module 3

apps/testingaccessibility/src/lib/modules.ts, apps/testingaccessibility/src/pages/api/certificate/modules/[slug].ts, apps/testingaccessibility/src/pages/learn/[module]/index.tsx, apps/testingaccessibility/src/utils/draw-certificate.ts, apps/testingaccessibility/src/utils/fetch-base64-image.ts
following up to suggestions from https://github.com/skillrecordings/products/pull/276#pullrequestreview-1012456798
=> update(testingaccessibility): extract certificate and module utils

apps/testingaccessibility/studio/schemas/objects/callout.js
=> Adds exercise callout

packages/player/package.json, packages/player/src/actions/index.ts, packages/player/src/components/hls-source.tsx, packages/player/src/components/video.tsx, pnpm-lock.yaml
https://www.loom.com/share/2561b0808c774c6e95191999cc7ad6cc
=> fix(player): update the hls lib to prevent video freezes

apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/pages/index.tsx, apps/testingaccessibility/src/styles/pricing.css, apps/testingaccessibility/src/utils/format-prices-for-product.ts, apps/testingaccessibility/src/utils/get-coupon-label.ts
=> update(testingaccessibility): PPP box design + better sale indication

apps/testingaccessibility/src/components/content/new-landing-copy.mdx, apps/testingaccessibility/src/components/mdx/index.tsx, apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/components/primary-newsletter-cta.tsx, apps/testingaccessibility/src/pages/buy.tsx, apps/testingaccessibility/src/pages/index.tsx
Made a few copy updates. I'll probably have more as I go through Sanity, but those can be in another PR.
=> Copy updates and section landmark labels

apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/components/product-tiers.tsx, apps/testingaccessibility/src/context/pricing-check-context.tsx, apps/testingaccessibility/src/pages/api/prices.ts, packages/scripts/jest/next/jest-preset.js
disallow (soft) purchase of a tier below their purchased tiers
=> feat(testingaccessibility): add a downgrade block in price tiers

apps/testingaccessibility/src/lib/prisma-api.ts, apps/testingaccessibility/src/lib/purchases.ts, apps/testingaccessibility/src/pages/api/redeem.ts, apps/testingaccessibility/src/pages/api/stripe/checkout.ts, apps/testingaccessibility/src/pages/thanks/redeem.tsx, apps/testingaccessibility/src/pages/welcome/index.tsx, apps/testingaccessibility/src/server/ability.ts
checking if purchases are valid for various things where you'd want a valid purchase
=> feat(testingaccessibility): check to make sure previous purchases are valid

apps/testingaccessibility/src/components/app/layout.tsx, apps/testingaccessibility/src/components/app/navigation.tsx, apps/testingaccessibility/src/components/portable-text/index.tsx, apps/testingaccessibility/src/components/portable-text/table-of-contents.tsx, apps/testingaccessibility/src/components/search/autocomplete.tsx, apps/testingaccessibility/src/pages/accessibility-reviews/[slug].tsx, apps/testingaccessibility/src/pages/accessibility-reviews/index.tsx, apps/testingaccessibility/src/pages/articles.tsx, apps/testingaccessibility/src/pages/buy.tsx, apps/testingaccessibility/src/pages/credits.tsx, apps/testingaccessibility/src/pages/index.tsx, apps/testingaccessibility/src/pages/invoices/[merchantChargeId].tsx, apps/testingaccessibility/src/pages/learn/index.tsx, apps/testingaccessibility/src/pages/role.tsx, apps/testingaccessibility/src/pages/thanks/purchase.tsx, apps/testingaccessibility/src/pages/welcome/index.tsx, apps/testingaccessibility/src/pages/workshops/index.tsx, apps/testingaccessibility/src/templates/article-template.tsx, apps/testingaccessibility/src/templates/lesson-template.tsx, apps/testingaccessibility/src/templates/live-workshop-template.tsx, apps/testingaccessibility/src/templates/module-template.tsx, apps/testingaccessibility/src/templates/section-template.tsx
A big batch of updates as I went through the platform. I'm opening issues for the things that I had to punt on, or needed more input.
Please help me test these changes, as I couldn't confirm them on production without a full local setup!
=> Accessibility updates: 070922

apps/testingaccessibility/src/pages/api/prices.ts
=> fix(testingaccessibility): default country

apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/pages/api/prices.ts, apps/testingaccessibility/src/utils/format-prices-for-product.test.ts, apps/testingaccessibility/src/utils/format-prices-for-product.ts
=> fix(testingaccessibility): ppp checkout coupons now function as expected

apps/testingaccessibility/src/components/product-tiers.tsx, apps/testingaccessibility/src/pages/api/admin/coupon.ts, apps/testingaccessibility/src/styles/pricing.css
=> feat(testingaccessibility): ability to generate various percentage off coupons

apps/testingaccessibility/src/lib/products.ts, apps/testingaccessibility/src/utils/props-for-commerce.ts, apps/testingaccessibility/studio/deskStructure.js, apps/testingaccessibility/studio/schemas/documents/pricing.js, apps/testingaccessibility/studio/schemas/schema.js, apps/testingaccessibility/studio/src/structure/pricing.js
I was confused by the "order documents" plugin and thought this would be clearer
=> feat(testingaccessibility): pricing as a top level item in sanity to sort products

apps/testingaccessibility/src/templates/lesson-template.tsx
=> fix(testingaccessibility): lesson progress toggle

apps/testingaccessibility/src/pages/learn/index.tsx, apps/testingaccessibility/src/pages/welcome/index.tsx
=> fix(testingaccessibility): contrast issues

apps/testingaccessibility/src/components/portable-text/index.tsx, apps/testingaccessibility/studio/schemas/objects/body.js
=> update(testingaccessibility): code blocks

apps/testingaccessibility/src/components/app/layout.tsx, apps/testingaccessibility/src/components/sale-banner.tsx, apps/testingaccessibility/src/pages/buy.tsx, apps/testingaccessibility/src/pages/index.tsx
=> update(sale banner): no need to pass products + improve a11y

apps/testingaccessibility/src/pages/error/index.tsx, apps/testingaccessibility/src/pages/login.tsx, pnpm-lock.yaml
=> feat(testingaccessibility): gives better error for reused link

apps/protailwind/src/components/scenes/city/camera.tsx, apps/protailwind/src/components/scenes/city/index.tsx
=> update(protailwind): limit dpr to improve perf

apps/testingaccessibility/src/components/app/footer.tsx, apps/testingaccessibility/src/components/primary-newsletter-cta.tsx, apps/testingaccessibility/src/pages/newsletter.tsx
* Adds a newsletter page at `/newsletter`
* Adds "Newsletter" to footer (screenshot shows prior "Newsletter Signup" text)
* Uses the PrimaryCTA component with Email course text
* Will display "It looks like you're already signed up!" if they are recognized
=> Add a newsletter page with signup form to TA

apps/testingaccessibility/src/components/app/navigation.tsx, apps/testingaccessibility/src/hooks/use-current-ability.ts, apps/testingaccessibility/src/hooks/use-nav-state.ts, apps/testingaccessibility/src/hooks/use-user.ts, apps/testingaccessibility/src/server/ability.ts
=> feat(testingaccessibility): show nav faster :zap:

apps/testingaccessibility/src/components/contact/contact-email-field.tsx, apps/testingaccessibility/src/components/contact/contact-form.tsx, apps/testingaccessibility/src/components/feedback/fields.tsx, apps/testingaccessibility/src/components/feedback/form.tsx, apps/testingaccessibility/src/pages/contact.tsx
- fixed email field for non signed in users
- tweaked design and wording
=> update(testingaccessibility): contact

apps/total-typescript/src/pages/index.tsx
=> chore(total-typescript): update copy 

apps/testingaccessibility/src/hooks/use-feedback-form.ts, packages/skill-api/src/core/services/send-feedback-from-user.ts
fix feedback url and disable posting to slack from dev env
=> fix(testingaccessibility): feedback url

apps/protailwind/src/pages/answer.tsx
=> chore(protailwind): update tagID to reflect CK automated sequence

apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/context/pricing-check-context.tsx, apps/testingaccessibility/src/utils/get-coupon-label.ts
=> chore(testingaccessibility): display upgrade pricing info

apps/protailwind/package.json, apps/testingaccessibility/src/lib/prisma-api.ts, apps/testingaccessibility/src/utils/record-new-purchase.ts, packages/database/package.json, packages/database/prisma/schema.prisma, pnpm-lock.yaml
=> chore(database): upgrade to prisma 4

apps/testingaccessibility/src/styles/globals.css, packages/player/package.json, packages/player/src/components/controls/playback-rate-menu-button-control.tsx, packages/player/src/components/listbox/listbox-button.tsx, packages/player/src/styles/scss/components/listbox.scss, pnpm-lock.yaml
=> chore(player): refactor listbox to use radix

packages/quiz/src/pages/api/answer.ts, packages/skill-api/src/core/services/convertkit/convertkit-answer-quiz-question.ts
=> fix(quiz): answer

apps/fronttoback/src/components/landing-copy.mdx
* Fixes missing "s" and "NoSQL" typos
* Update alignment in grid
Before:
After:
=> Fix fronttoback typos & alignment

apps/fronttoback/next.config.js, apps/fronttoback/package.json, apps/fronttoback/src/components/app/navigation.tsx, apps/fronttoback/src/lib/articles.ts, apps/fronttoback/src/pages/[article].tsx, apps/fronttoback/src/pages/_document.tsx, apps/fronttoback/src/pages/articles.tsx, apps/fronttoback/src/pages/index.tsx, apps/fronttoback/src/pages/server-sitemap.xml/index.tsx, apps/fronttoback/src/styles/globals.css, apps/fronttoback/src/templates/article-template.tsx, apps/fronttoback/studio/schemas/documents/article.js, apps/fronttoback/studio/schemas/schema.js, apps/fronttoback/tailwind.config.js, pnpm-lock.yaml
this setups up article routes (/articles & /article-slug) and enables simplified preview from sanity on fronttoback.dev.
next step will be applying styles.
=> feat(fronttoback): articles spike

apps/badass/src/styles/globals.css
=> fix(badass): add the gap between form elements

apps/escuela-frontend/.env.development, apps/escuela-frontend/.env.production
=> adding ogimages url for EF

apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/hooks/use-convertkit.tsx
=> fix(tt): cleaner subscriber url param removal

apps/protailwind/package.json, apps/protailwind/src/lib/articles.ts, apps/protailwind/src/pages/[article].tsx, apps/protailwind/src/pages/articles.tsx, apps/protailwind/src/templates/article-template.tsx, apps/protailwind/src/utils/is-browser.ts, apps/protailwind/studio/schemas/documents/article.js, pnpm-lock.yaml
=> feat(protwailwind): improve articles seo and performance

apps/testingaccessibility/src/components/team/buy-more-seats.tsx, apps/testingaccessibility/src/components/team/card.tsx, apps/testingaccessibility/src/pages/team/index.tsx, apps/testingaccessibility/src/pages/welcome/index.tsx
example:
```jsx
import BuyMoreSeats from “components/team/buy-more-seats”
<Card
title={{content: “Get more seats”, as: “h2”}}
icon={
<TicketIcon className="w-5 text-green-500" aria-hidden="true" />
}
>
<BuyMoreSeats />
</Card>
```
=> feat(ta): `BuyMoreSeats` widget template

apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/styles/newsletter.css, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/tip-template.tsx
=> feat(tt): tips subscribe form

apps/total-typescript/src/components/portable-text/index.tsx, apps/total-typescript/src/lib/tutorials.ts, apps/total-typescript/src/templates/tutorial-template.tsx, apps/total-typescript/studio/package.json, apps/total-typescript/studio/schemas/documents/exercise.js, apps/total-typescript/studio/schemas/documents/testimonial.js, apps/total-typescript/studio/schemas/objects/body.js, apps/total-typescript/studio/schemas/objects/bodyTestimonial.js, apps/total-typescript/studio/schemas/schema.js, apps/total-typescript/studio/yarn.lock
=> feat(tt): testimonials

packages/create-skill-app/create-app.ts, packages/create-skill-app/index.ts, packages/create-skill-app/templates/next/package.json
=> feat(csa): updated devPort in package.json

apps/testingaccessibility/README.md
This adds more detail and some planetscale specifics for how to create, evaluate, and deploy Prisma schema changes.
This is all based on what I picked up going through the whole process for https://github.com/skillrecordings/products/pull/510
=> docs(ta): how to test and deploy schema changes

apps/typescriptcourse/src/pages/podcast/[podcastSeason]/[podcastEpisode].tsx
=> chore(typescript-course): moving newsletter subscriber form up

apps/protailwind/package.json, apps/total-typescript/package.json, packages/quiz/package.json, pnpm-lock.yaml
`codesandbox/sandpack-react` package seems to be causing some weird build errors. checking if updating to latest will fix it.
=> chore: bump sandpack

apps/escuela-frontend/.env.development, apps/escuela-frontend/src/lib/articles.ts, apps/escuela-frontend/src/templates/article-template.tsx, apps/escuela-frontend/studio/schemas/documents/article.js, apps/escuela-frontend/studio/schemas/documents/collaborator.js, apps/escuela-frontend/studio/schemas/schema.js
=> feat(ef): add author in articles

apps/total-typescript/src/ability/ability.ts, apps/total-typescript/src/components/exercise/large-screen-module-lesson-list.tsx, apps/total-typescript/src/components/exercise/mobile-module-lesson-list.tsx, apps/total-typescript/src/components/lesson-list.tsx, apps/total-typescript/src/components/module-lesson-list-header.tsx, apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/offer/survey/index.tsx, apps/total-typescript/src/pages/_app.tsx, apps/total-typescript/src/server/routers/_app.ts, apps/total-typescript/src/server/routers/workshop.ts, apps/total-typescript/src/templates/exercise-template.tsx
=> feat(tt): use trpc to load CASL ability rules

apps/escuela-frontend/next.config.js
=> feat(ef): adding redirects from old site

apps/fronttoback/src/components/app/navigation.tsx, apps/fronttoback/src/components/app/subscribe-form.tsx, apps/fronttoback/src/components/portable-text/index.tsx, apps/fronttoback/src/styles/globals.css, apps/fronttoback/src/styles/prism.css, apps/fronttoback/src/templates/article-template.tsx
=> feat(ftb): adding navigation for articles 

apps/fronttoback/src/pages/articles.tsx
=> fix(ftb): adds key prop in articles page

apps/protailwind/src/components/exercise-overlay.tsx, apps/protailwind/src/components/navigation.tsx, apps/protailwind/src/components/portable-text/index.tsx, apps/protailwind/src/lib/exercises.ts, apps/protailwind/src/pages/tutorials/index.tsx, apps/protailwind/src/templates/exercise-template.tsx, apps/protailwind/studio/schemas/objects/body.js
=> chore(pro-tailwind): adds tutorials to nav

apps/protailwind/src/components/navigation.tsx
Fixing broken layout with horizontal scroll due to new navigation item in nav
=> fix(pt): responsive nav to avoid breaking layout

apps/protailwind/src/lib/exercises.ts, apps/protailwind/src/templates/exercise-template.tsx
=> fix: adding github url for solution

apps/total-typescript/src/ability/abilitiy.test.ts, apps/total-typescript/src/path-to-purchase-react/redeem-dialog.tsx, packages/ability/package.json, packages/ability/src/purchase-validators.test.ts, packages/ability/src/purchase-validators.ts, pnpm-lock.yaml
=> feat(tt): add tests for abilities

apps/escuela-frontend/src/components/exercise-navigator.tsx, apps/escuela-frontend/src/components/exercise-overlay.tsx, apps/escuela-frontend/src/components/github-link.tsx, apps/escuela-frontend/src/components/stackblitz-iframe.tsx, apps/escuela-frontend/src/lib/exercises.ts, apps/escuela-frontend/src/pages/articulos.tsx, apps/escuela-frontend/src/pages/index.tsx, apps/escuela-frontend/src/pages/tutoriales/index.tsx, apps/escuela-frontend/src/styles/prism.css, apps/escuela-frontend/src/templates/exercise-template.tsx, apps/escuela-frontend/src/templates/tip-template.tsx, apps/escuela-frontend/src/templates/tutorial-template.tsx, apps/escuela-frontend/studio/schemas/objects/github.js
=> chore(ef): fix and design updates

apps/total-typescript/package.json, apps/total-typescript/src/templates/workshop-template.tsx, pnpm-lock.yaml
=> feat(tt): style workshop ToC

apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/components/exercise/video.tsx, apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/utils/get-next-section.ts
this makes `handleContinue` function to work for workshops by taking sections into account.
=> feat(tt): get next lesson in section

apps/testingaccessibility/src/pages/thanks/purchase.tsx
=> refactor(ta): use existing SDK method for DB call

apps/total-typescript/src/server/routers/progress.ts, apps/total-typescript/src/templates/workshop-template.tsx, packages/database/src/prisma-api.ts
=> feat(tt): getProgress sdk

apps/testingaccessibility/src/components/sale-banner.tsx, apps/testingaccessibility/src/lib/reviews.ts, apps/testingaccessibility/src/pages/accessibility-reviews/[slug].tsx, apps/testingaccessibility/studio/schemas/documents/review.js
=> feat(ta): review body

apps/engmanagement/src/components/redeem-dialog.tsx, apps/engmanagement/src/utils/handle-self-redeem.ts, apps/epic-web/src/pages/api/auth/[...nextauth].ts, apps/keyboardlegend/src/pages/api/auth/[...nextauth].ts, apps/testingaccessibility/src/components/redeem-dialog.tsx, apps/testingaccessibility/src/pages/api/auth/[...nextauth].ts, apps/testingaccessibility/src/utils/handle-self-redeem.ts, apps/total-typescript/src/pages/api/auth/[...nextauth].ts, apps/total-typescript/src/pages/welcome/index.tsx, apps/total-typescript/src/path-to-purchase-react/handle-self-redeem.ts, apps/total-typescript/src/path-to-purchase-react/redeem-dialog.tsx, packages/create-skill-app/templates/next/src/pages/api/auth/[...nextauth].ts, packages/skill-api/src/core/index.ts, packages/skill-api/src/core/services/redeem-golden-ticket.ts, packages/skill-api/src/server/default-next-auth-options.ts
=> feat(commerce): path to purchase tweaks

apps/total-typescript/src/components/module-lesson-list-header.tsx
=> feat(tt): add a section to the lesson list

apps/total-typescript/package.json, apps/total-typescript/src/offer/survey/index.tsx, apps/total-typescript/src/path-to-purchase-react/pricing.tsx, apps/total-typescript/src/styles/pricing.css, pnpm-lock.yaml
https://www.loom.com/share/52bfa08de2a44855ac8b68d0541afd74
=> feat(tt): tweak the pricing grid

apps/kcdbundle/src/components/commerce/purchase.tsx, apps/kcdbundle/src/config.js, apps/testingaccessibility/src/config.js
=> reset(kcd): reset pricing

apps/total-typescript/studio/schemas/documents/explainer.js, apps/total-typescript/studio/schemas/documents/module.js, apps/total-typescript/studio/schemas/schema.js
=> feat(tt): add explainer document type

apps/total-typescript/src/components/lesson-list.tsx, apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/lib/sections.ts, apps/total-typescript/src/lib/tutorials.ts, apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/index.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/solution.tsx
=> feat(tt): adds explainer lesson type to ui

apps/total-typescript/src/components/primary-newsletter-cta.tsx, apps/total-typescript/src/pages/newsletter.tsx, apps/total-typescript/src/schemas/subscriber.ts, apps/total-typescript/src/server/analytics-server.ts, apps/total-typescript/src/server/ck-set-subscriber-cookie.ts, apps/total-typescript/src/server/ck-subscriber-from-cookie.ts, apps/total-typescript/src/server/routers/abilities.ts, apps/total-typescript/src/server/routers/convertkit.ts, apps/total-typescript/src/server/routers/progress.ts, apps/total-typescript/src/server/routers/subscriber.ts
=> fix(tt) purchase cta disappears on home page

apps/total-typescript/src/components/app/navigation.tsx, apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/components/module-lesson-list-header.tsx, apps/total-typescript/src/components/portable-text/index.tsx, apps/total-typescript/src/components/primary-newsletter-cta.tsx, apps/total-typescript/src/components/share.tsx, apps/total-typescript/src/lib/articles.ts, apps/total-typescript/src/pages/[article].tsx, apps/total-typescript/src/pages/api/og.tsx, apps/total-typescript/src/pages/articles.tsx, apps/total-typescript/src/pages/rss.xml.ts, apps/total-typescript/src/styles/newsletter.css, apps/total-typescript/src/templates/article-template.tsx, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/studio/deskStructure.js, apps/total-typescript/studio/schemas/documents/article.js, apps/total-typescript/studio/schemas/schema.js, apps/total-typescript/studio/src/structure/articles.js
=> feat(tt): articles

apps/testingaccessibility/src/components/content/faq.ts, apps/testingaccessibility/src/pages/boss.mdx
* Adds "boss" letter
* Updates FAQ section
=> [TA] Add boss letter and update faqs

apps/total-typescript/src/server/get-middleware-response.ts
=> hotfix(tt): disappearing purchase CTA

apps/total-typescript/src/components/primary-newsletter-cta.tsx, apps/total-typescript/src/styles/newsletter.css, apps/total-typescript/src/templates/article-template.tsx
=> feat(tt): article cta with ck field & arrow

apps/total-typescript/package.json, apps/total-typescript/src/path-to-purchase-react/pricing.tsx, apps/total-typescript/src/styles/pricing.css, packages/commerce-server/src/record-new-purchase.ts, packages/database/src/prisma-api.ts, packages/skill-api/src/core/services/stripe-checkout.ts, pnpm-lock.yaml
=> feat(tt): pricing team switch

apps/total-typescript/src/path-to-purchase-react/pricing.tsx, apps/total-typescript/src/server/routers/_app.ts, apps/total-typescript/src/server/routers/pricing.ts, apps/total-typescript/src/team/buy-more-seats.tsx, packages/commerce-server/src/get-active-merchant-coupon.ts, packages/skill-api/src/core/services/load-prices.ts
This is the first step in a process to move this kind of query into the
skill-api package so that it can be shared by other apps. That process
will eventually lead to upgrading tRPC to v10 as well.
=> feat(tt): move price formatting to tRPC query

apps/transcript-automation/src/components/primary-newsletter-cta.tsx, apps/transcript-automation/src/content/home.md
* Updates landing page copy for Transcript Automation
=> [TAuto] Update landing page copy

apps/total-typescript/src/components/exercise/video.tsx, apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/lib/video-resource.ts, apps/total-typescript/src/pages/api/video-thumb.ts, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/index.tsx, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/solution.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/index.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/solution.tsx, apps/total-typescript/src/server/routers/_app.ts, apps/total-typescript/src/server/routers/video-resources.ts, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx, apps/total-typescript/src/utils/get-base-url.ts, apps/total-typescript/src/utils/trpc.ts, apps/total-typescript/src/video/use-video-resource.tsx
=> load video resources instead of attaching playback id to lesson

apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/components/exercise/exercise-description.tsx, apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/lib/tips.ts, apps/total-typescript/src/pages/tips/[tip].tsx, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/index.tsx, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/solution.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/index.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/solution.tsx, apps/total-typescript/src/schemas/subscriber.ts, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/tip-template.tsx, apps/total-typescript/src/utils/analytics.ts, apps/total-typescript/src/video/use-lesson.tsx, apps/total-typescript/src/video/use-next-lesson.ts
this moves the lesson info OUT of the "video provider" and into a dedicated lesson provider
=> introduce lesson provider

apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/components/exercise/video.tsx, apps/total-typescript/src/hooks/use-mux-player.tsx, apps/total-typescript/src/lib/video-resource.ts, apps/total-typescript/src/pages/tips/[tip].tsx, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/index.tsx, apps/total-typescript/src/pages/tutorials/[module]/[exercise]/solution.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/index.tsx, apps/total-typescript/src/pages/workshops/[module]/[section]/[exercise]/solution.tsx, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/tip-template.tsx, apps/total-typescript/src/utils/get-base-url.ts, apps/total-typescript/src/video/use-video-resource.tsx
=> add video resource id to context for use while loading

apps/total-typescript/src/video/exercise-overlay.tsx, packages/skill-lesson/server/routers/modules.ts
=> fix(tt): bring back subscribe form on tutorials

apps/total-typescript/src/team/index.tsx
=> feat(tt): increment seat use count for self-claim

apps/total-typescript/src/pages/team/buy-more-seats.tsx
If the URL query params include a `productId` we look up the product for the 'Buy More Seats' component that way. Otherwise we fallback to the user's bulk or individual purchase for a product ID.
Based on looking up the product by `productId`, we are able to get and display the product's name.
=> feat(tt): 'Buy More Seats' is aware of productId

apps/typescriptcourse/src/components/exercise-overlay.tsx, apps/typescriptcourse/src/pages/tutorials/index.tsx
Adds a few design changes to the tutorials
=> minor design changes

apps/typescriptcourse/src/components/exercise-overlay.tsx, apps/typescriptcourse/src/styles/globals.css, apps/typescriptcourse/src/templates/tuturial-template.tsx
=> Fix TC-4: fix minor UI issues

apps/protailwind/src/templates/workshop-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx
=> some lessons aren't exercises so show progress

apps/total-typescript/src/components/landing-copy.mdx, apps/total-typescript/src/templates/home-template.tsx
=> feat(tt): swap out pricing for subscribe form

packages/skill-lesson/trpc/routers/lessons.ts
=> fix: fix next lesson logic for explainers

apps/protailwind/src/components/layout.tsx, apps/protailwind/src/pages/workshops/index.tsx
=> feat(pt): adding all og:tags for each page

apps/protailwind/process.d.ts, apps/protailwind/src/pages/api/skill/[...skillRecordings].ts
=> feat(pt): connect slack announce channel

apps/protailwind/src/lib/workshops.ts, apps/protailwind/src/pages/workshops/index.tsx, apps/protailwind/src/templates/workshop-template.tsx
=> feat(pt): highlight toc for purchasers

apps/total-typescript/src/hooks/use-progress.test.ts, apps/total-typescript/src/hooks/use-progress.ts, apps/total-typescript/src/templates/workshop-template.tsx
=> using lesson id and not solution slugs for progress

apps/protailwind/src/pages/workshops/[module]/index.tsx, apps/protailwind/src/server/routers/_app.ts, apps/protailwind/src/server/routers/module-progress.ts, apps/protailwind/src/templates/workshop-template.tsx, apps/protailwind/src/video/exercise-overlay.tsx, apps/protailwind/src/video/module-progress.ts, packages/skill-lesson/schemas/resource.ts
=> refactor(pt): use module progress router

apps/protailwind/package.json, apps/protailwind/src/components/layout.tsx, apps/protailwind/src/components/navigation.tsx, apps/protailwind/src/pages/_app.tsx, apps/protailwind/src/styles/globals.css, packages/feedback-widget/.eslintrc.js, packages/feedback-widget/README.md, packages/feedback-widget/config/jest/cssTransform.js, packages/feedback-widget/package.json, packages/feedback-widget/src/dialog.tsx, packages/feedback-widget/src/feedback-context.tsx, packages/feedback-widget/src/feedback-dialog.tsx, packages/feedback-widget/src/fields.tsx, packages/feedback-widget/src/form.tsx, packages/feedback-widget/src/index.ts, packages/feedback-widget/src/spinner.tsx, packages/feedback-widget/src/styles.css, packages/feedback-widget/src/use-feedback-widget.ts, packages/feedback-widget/tsconfig.json, pnpm-lock.yaml
=> feat(pt): feedback widget

apps/protailwind/src/templates/workshop-template.tsx, packages/skill-lesson/hooks/use-global-player-shortcut.ts
=> fix(skill-lesson): fullscreen shortcut

packages/skill-lesson/hooks/use-mux-player.tsx
Commented out the `router.push` for now just to avoid confuse the users.
=> Fix navigate to /exercise

apps/protailwind/src/trpc/routers/module-progress.ts, apps/protailwind/src/video/lesson-list.tsx, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx, apps/total-typescript/src/trpc/routers/module-progress.ts, apps/total-typescript/src/video/lesson-list.tsx, apps/total-typescript/src/video/module-lesson-list-header.tsx, apps/total-typescript/src/video/module-progress.ts
https://user-images.githubusercontent.com/25487857/217309991-c1be96f4-2934-44aa-8208-97c1a75fd7ea.mp4
=> feat(tt): display progress & sections on lesson pages

apps/protailwind/src/trpc/routers/module-progress.ts, apps/protailwind/src/video/lesson-list.tsx, apps/total-typescript/package.json, apps/total-typescript/src/pages/tutorials/[module]/index.tsx, apps/total-typescript/src/pages/tutorials/index.tsx, apps/total-typescript/src/pages/workshops/index.tsx, apps/total-typescript/src/templates/tutorial-template.tsx, apps/total-typescript/src/trpc/routers/module-progress.ts, apps/total-typescript/src/video/lesson-list.tsx, apps/total-typescript/src/video/module-progress.ts, packages/skill-lesson/lib/modules.ts, pnpm-lock.yaml
=> update(tt): address feedback from #789

apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/templates/tip-template.tsx, apps/total-typescript/src/video/module-lesson-list-header.tsx, packages/skill-lesson/hooks/use-mux-player.tsx, packages/skill-lesson/hooks/use-player-prefs.ts
=> feat(skill-lesson): persist CC preference

apps/total-typescript/src/templates/workshop-template.tsx
=> fix(tt): long section title looking bad

apps/total-typescript/src/pages/invoices/index.tsx, apps/total-typescript/src/pages/team/index.tsx, apps/total-typescript/src/pages/thanks/purchase.tsx, apps/total-typescript/src/pages/thanks/redeem.tsx, apps/total-typescript/src/pages/welcome/index.tsx, apps/total-typescript/src/team/card.tsx, apps/total-typescript/src/team/index.tsx, apps/total-typescript/src/team/self-redeem-button.tsx
=> feat(tt): improve purchase path design

apps/protailwind/src/pages/invoices/[merchantChargeId].tsx, apps/total-typescript/src/pages/invoices/[merchantChargeId].tsx
=> feat: forward invoice functionality

apps/protailwind/src/team/self-redeem-button.tsx, apps/protailwind/src/trpc/routers/_app.ts, apps/protailwind/src/trpc/routers/purchases.ts, apps/protailwind/src/video/exercise-overlay.tsx, apps/total-typescript/src/team/self-redeem-button.tsx, apps/total-typescript/src/trpc/routers/_app.ts, apps/total-typescript/src/trpc/routers/purchases.ts, apps/total-typescript/src/video/exercise-overlay.tsx, packages/skill-lesson/hooks/use-mux-player.tsx
This is a spike and request for feedback. **It does not cover scenario when user used up all of their seats or any improvements to email communication.** That said, I think it's pretty useful as is. Clicking "claim" will refetch abilities and unlock the content right away without having to refresh the page.
=> feat: spike team aware workshop purchase CTA

apps/typescriptcourse/src/components/exercise-overlay.tsx, apps/typescriptcourse/tailwind.config.js
Should be good now:
https://share.getcloudapp.com/2Nu6gnJD
(gif is too big to upload)
=> fix layout

apps/total-typescript/src/pages/products/[slug].tsx, apps/total-typescript/src/path-to-purchase-react/pricing.tsx, apps/total-typescript/src/path-to-purchase-react/products.server.ts, apps/total-typescript/studio/deskStructure.js, apps/total-typescript/studio/schemas/documents/module.js, apps/total-typescript/studio/schemas/documents/product.js, apps/total-typescript/studio/src/structure/playlists.js, packages/commerce-server/src/@types/index.ts
* introduces a playlist module type
=> adds a product page

apps/total-typescript/src/pages/team/buy-more-seats.tsx, apps/total-typescript/src/styles/pricing.css
I think I made it look "good enough" for a first pass, but I'd appreciate @vojtaholik's thoughts on the overall layout,  design, and effectiveness of this page.
=> feat(tt): show product description on Buy More Seats

apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/lib/playlists.ts, apps/total-typescript/src/lib/tutorials.ts, apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/module-builder/use-file-change.ts, apps/total-typescript/src/pages/playlists/[module]/[lesson].tsx, apps/total-typescript/src/pages/playlists/[module]/index.tsx, apps/total-typescript/src/pages/playlists/index.tsx, apps/total-typescript/src/templates/playlist-template.tsx, apps/total-typescript/src/templates/tutorial-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx, apps/total-typescript/src/video/lesson-title.tsx, apps/total-typescript/src/video/portable-text/index.tsx, apps/total-typescript/studio/schemas/documents/interview.js, apps/total-typescript/studio/schemas/documents/module.js, apps/total-typescript/studio/schemas/schema.js, packages/skill-lesson/lib/lesson-resource.ts, packages/skill-lesson/lib/modules.ts, packages/skill-lesson/utils/ability.ts
This roughs in /playlists based on /tutorials
Everything is loaded and auth'd, but data is sparse and it likely needs some layout love.
=> adds /playlists routes for displaying video playlists

apps/total-typescript/src/video/lesson-list.tsx
testing this out to see how it feels.
=> update(tt): lesson list to close prev section

apps/colt-steele/src/pages/_app.tsx, apps/protailwind/src/pages/_app.tsx, apps/technical-interviews/src/pages/_app.tsx, apps/total-typescript/src/pages/_app.tsx, apps/typescriptcourse/src/pages/_app.tsx, packages/create-skill-app/templates/next/.config-templates/package-template.json, packages/create-skill-app/templates/next/src/pages/_app.tsx
this was causing issues with trpc query/router invalidation
thanks @c-ehrlich for the fix
=> `withTRPC` provides the query client so no need for the additional tag

apps/total-typescript/studio/schemas/documents/module.js, apps/total-typescript/studio/schemas/documents/section.js
Reverts skillrecordings/products#823
These changes would break the module documents if deployed
=> Revert "TT-162 adjust schema to disallow exercises and explainers in module"

packages/skill-lesson/hooks/use-mux-player.tsx
=> fix(tt): navigating to /exercise from /exercise

apps/total-typescript/src/path-to-purchase-react/pricing.tsx
=> fix(tt): `allowPurchase` was false in purchase CTA

apps/total-typescript/src/components/app/navigation.tsx, apps/total-typescript/src/components/icons.tsx, apps/total-typescript/src/pages/purchases/[purchaseId].tsx, apps/total-typescript/src/pages/purchases/index.tsx, apps/total-typescript/src/purchase-details/purchase-details-template.tsx, apps/total-typescript/src/purchase-details/purchases-index-template.tsx, apps/total-typescript/src/purchase-transfer/purchase-transfer.tsx, apps/total-typescript/src/styles/purchase-transfer.css
=> feat(tt): purchases routes

apps/protailwind/src/purchase-details/purchase-details-template.tsx, apps/total-typescript/src/components/app/navigation.tsx, apps/total-typescript/src/purchase-details/purchase-details-template.tsx, apps/total-typescript/src/purchase-details/purchases-index-template.tsx
=> update(tt): purchases

apps/total-typescript/src/trpc/routers/abilities.ts, packages/skill-lesson/lib/products.ts, packages/skill-lesson/trpc/routers/modules.ts
=> hotfix(pt): ability to view content

apps/total-typescript/src/templates/workshop-template.tsx
=> feat(tt): indicate locked lessons

apps/protailwind/src/video/exercise-overlay.tsx
=> Fixes PT-113: Animated Stripes Tutorial Exercise Overlay has extra "or"

apps/total-typescript/src/lib/tutorials.ts, apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/templates/tutorial-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx, apps/total-typescript/src/testimonials/index.tsx, apps/total-typescript/src/video/portable-text/index.tsx, apps/total-typescript/studio/schemas/documents/module.js, packages/skill-lesson/schemas/module.ts, packages/skill-lesson/schemas/testimonial.ts
=> feat(tt): module testimonials

apps/technical-interviews/package.json, pnpm-lock.yaml
this is an attempt to fix technical interview's failing build.
=> fix(ti): build

apps/protailwind/src/video/video.tsx, apps/total-typescript/src/video/video.tsx
=> do not restart the video on tab focus

apps/epic-web/src/pages/api/webhooks/castingwords.ts, apps/epic-web/studio/deskStructure.js, apps/epic-web/studio/schemas/documents/exercise.js, apps/epic-web/studio/schemas/documents/explainer.js, apps/epic-web/studio/schemas/documents/lesson.js, apps/epic-web/studio/schemas/documents/module.js, apps/epic-web/studio/schemas/documents/section.js, apps/epic-web/studio/schemas/objects/feature.js, apps/epic-web/studio/schemas/objects/github-repo.js, apps/epic-web/studio/schemas/objects/resources/github.js, apps/epic-web/studio/schemas/objects/resources/gitpod.js, apps/epic-web/studio/schemas/objects/resources/muxVideo.js, apps/epic-web/studio/schemas/objects/resources/product.js, apps/epic-web/studio/schemas/objects/resources/solution.js, apps/epic-web/studio/schemas/schema.js, apps/epic-web/studio/src/structure/tutorials.js, apps/epic-web/studio/src/structure/workshops.js, package.json, pnpm-lock.yaml
=> feat(ew): adds tutorial (module) structure

apps/total-typescript/src/pages/thanks/purchase.tsx, packages/skill-lesson/trpc/routers/purchaseUserTransfer.ts
=> feat(tt): allow a purchase transfer on the pre-login "thanks" page

apps/epic-web/studio/schemas/objects/github-repo.js
=> quick copy fix

apps/protailwind/src/pages/tutorials/[module]/[section]/[lesson]/index.tsx
=> fix(pt): correct repl dir

apps/scriptkit/package.json, apps/scriptkit/scripts/update-hot.ts, apps/scriptkit/scripts/write-course-data.ts, apps/scriptkit/scripts/write-repo-scripts-data.ts, pnpm-lock.yaml, turbo.json
=> fix(scriptkit): Upgrade kit, fix prebuild, remove hanging test script, use "projectPath" in scripts

apps/scriptkit/src/lib/get-user-scripts.ts
=> fix(release): add per_page 100, the default 30 was only finding prereleases

apps/total-typescript/src/pages/team/index.tsx, packages/skill-lesson/team/claimed-team-seats.tsx, packages/skill-lesson/trpc/routers/_skill-lesson-router.ts, packages/skill-lesson/trpc/routers/coupons.ts
@vojtaholik I made it look presentable to solve this particular user issue, but this expands the page and the cards don't like it.
=> adds ability to see claimed seats for bulk

apps/scriptkit/package.json, pnpm-lock.yaml
prev build failed due to a kit sdk error: https://vercel.com/skillrecordings/scriptkit/7jfbTcRcRXoxLb2FELkTGeBH6ity?filter=all
Upgrading kit to latest
=> fix(build): update kit sdk

apps/testing-javascript/package.json, apps/testing-javascript/schemas/documents/article.jsx, apps/testing-javascript/src/components/navigation.tsx, apps/testing-javascript/src/pages/buy.tsx, apps/testing-javascript/src/pages/purchases/[purchaseId].tsx, apps/testing-javascript/src/pages/purchases/index.tsx, apps/testing-javascript/src/pages/thanks/purchase.tsx, apps/testing-javascript/src/pages/transfer/[purchaseUserTransferId].tsx, apps/testing-javascript/src/pages/welcome/index.tsx, apps/testing-javascript/src/path-to-purchase-react/pricing-check-context.tsx, apps/testing-javascript/src/path-to-purchase-react/pricing.tsx, apps/testing-javascript/src/purchase-details/purchase-details-template.tsx, apps/testing-javascript/src/purchase-details/purchase-details.css, apps/testing-javascript/src/purchase-details/purchases-index-template.tsx, apps/testing-javascript/src/purchase-transfer/purchase-transfer.tsx, apps/testing-javascript/src/server/products.server.ts, packages/skill-lesson/icons/index.tsx, pnpm-lock.yaml
This implements `/purchase`, `/thanks`, `/welcome`, `/transfer` pages:
<details>
<summary>Purchases</summary>
</details>
<details>
<summary>Purchase details</summary>
</details>
<details>
<summary>Purchase transfer completed</summary>
</details>
<details>
<summary>Accept transfer</summary>
</details>
<details>
<summary>Thanks</summary>
</details>
<details>
<summary>Welcome</summary>
</details>
While testing these pages I found the following issues:
1. After transfer is completed Purchase link doesn’t appear in dropdown menu (and appears after reload)
2. If user has two products purchased, one for individual use and second for team, after transfer individual product team product gets transferred also.
3. Discount appears only on 10+ copies, but should occur with 5+ copies
=> Fixes TJS-25: purchase flow iteration #3

apps/total-typescript/.vscode/settings.json, apps/total-typescript/src/pages/search.tsx, apps/total-typescript/src/trpc/routers/_app.ts, apps/total-typescript/src/trpc/routers/search.ts, pnpm-lock.yaml
Rudimentary search, but it works well!
How can we integrate it?
=> initial spike for a search feature

apps/scriptkit/src/pages/api/kenv.ts
=> fix(api): add kenv install link

apps/protailwind/src/purchase-details/purchase-details-template.tsx
=> fix a link issue in purchases

apps/scriptkit/public/free-riders.json
=> fix(free-riders): Adding scythe to free-riders

apps/total-typescript/schemas/documents/cta.ts, apps/total-typescript/src/lib/tutorials.ts, packages/skill-lesson/schemas/module.ts, packages/skill-lesson/video/video-overlays.tsx
=> feat(tt): expiring overlay CTAs

apps/colt-steele/package.json, apps/colt-steele/src/pages/api/aws/sign-s3.ts, pnpm-lock.yaml
Colt Steele uploader it's throwing a 404 error. We are missing the sign-in logic to s3 to upload the video.
=> feat(cs): adding sign-s3

apps/testing-javascript/package.json, apps/testing-javascript/schemas/documents/module.jsx, apps/testing-javascript/src/components/certificate-form.tsx, apps/testing-javascript/src/components/landing/access-your-course.tsx, apps/testing-javascript/src/components/landing/what-is-in-testing-javascript.tsx, apps/testing-javascript/src/components/playlist/playlist-item.tsx, apps/testing-javascript/src/lib/playlists.ts, apps/testing-javascript/src/pages/api/certificate.tsx, apps/testing-javascript/src/pages/buy.tsx, apps/testing-javascript/src/pages/index.tsx, apps/testing-javascript/src/server/certificate.server.tsx, apps/testing-javascript/src/styles/miscellaneous.css, apps/testing-javascript/src/templates/landing-template.tsx, apps/testing-javascript/tailwind.config.js, pnpm-lock.yaml
<details>
<summary>Download Certificate</summary>
</details>
<details>
<summary>Preview Courses</summary>
</details>
Current videos are not original, have to get playbackID's.
=> Fixes TJS-35: Landing page: iteration #4

apps/badass/src/components/portable-text/index.tsx, apps/badass/src/templates/article-template.tsx, apps/badass/studio/schemas/objects/body.js, apps/badass/studio/schemas/objects/bodyImageFloated.js, apps/badass/studio/schemas/objects/specialHeading.js, apps/badass/studio/schemas/schema.js, apps/badass/tailwind.config.js
<details>
<summary>Desktop screenshot</summary>
</details>
<details>
<summary>Mobile screenshot</summary>
</details>
=> badass.dev: update article

apps/total-typescript/src/pages/concepts/[slug]/index.tsx, apps/total-typescript/src/pages/concepts/index.tsx, apps/total-typescript/src/styles/globals.css, packages/skill-lesson/markdown/serialize-mdx.ts
=> update(tt): concepts design

apps/colt-steele/src/components/app/navigation.tsx
=> feat(cs): adding tutorials in navbar

apps/total-typescript/package.json, pnpm-lock.yaml
Erroring here:
https://www.totaltypescript.com/concepts/how-to-use-ts-expect-error
But working here:
https://total-typescript-turbo-e0bt9wdbz-skillrecordings.vercel.app/concepts/how-to-use-ts-expect-error
=> Fix for twoslash on concepts page

apps/scriptkit/package.json, apps/scriptkit/src/pages/api/usage.ts, pnpm-lock.yaml
=> feat(usage): api for app events

apps/badass/src/templates/article-template.tsx
This is the final PR related to og images at badass.dev.
Removed subtitle from article page and clean up, updated data in Sanity.
=> Badass.dev: tweak badass articles og images

apps/epic-web/process.d.ts, apps/epic-web/src/pages/api/auth/[...nextauth].ts
=> enable github auth on epic web

apps/total-typescript/src/styles/globals.css, packages/skill-lesson/markdown/mdx-components.tsx
=> feat(sl): add MuxVideo comp

apps/epic-web/package.json, apps/epic-web/schemas/documents/product.tsx, apps/epic-web/seed_data/Product.00001.sql, apps/epic-web/src/lib/products.ts, apps/epic-web/src/pages/full-stack-workshop-series-vol-1.tsx, apps/epic-web/src/pages/invoices/[merchantChargeId].tsx, apps/epic-web/src/pages/invoices/index.tsx, apps/epic-web/src/pages/thanks/purchase.tsx, apps/epic-web/src/pages/thanks/redeem.tsx, apps/epic-web/src/pages/welcome/index.tsx, apps/epic-web/src/purchase-transfer/purchase-transfer.tsx, apps/epic-web/src/styles/commerce.css, apps/epic-web/src/styles/globals.css, apps/epic-web/src/templates/product-template.tsx, packages/skill-lesson/trpc/routers/pricing.ts, pnpm-lock.yaml
=> feat(epic-web): brings e-commerce to epic web

apps/epic-web/src/pages/invoices/index.tsx, apps/epic-web/src/pages/thanks/purchase.tsx, apps/epic-web/src/pages/welcome/index.tsx, apps/epic-web/src/templates/product-template.tsx, packages/skill-lesson/path-to-purchase/pricing.tsx
=> sell workshop tickets

apps/epic-web/src/pages/invoices/[merchantChargeId].tsx, apps/epic-web/src/pages/invoices/index.tsx, apps/epic-web/src/pages/thanks/purchase.tsx, apps/epic-web/src/pages/welcome/index.tsx, apps/epic-web/src/purchase-transfer/purchase-transfer.tsx, apps/epic-web/src/styles/globals.css, apps/epic-web/src/styles/team.css
=> feat(ew): add styles for after purchase

apps/badass/src/components/mdx/components/accented-title.tsx, apps/badass/src/components/mdx/components/callout-title.tsx, apps/badass/src/components/mdx/components/image-with-caption.tsx, apps/badass/src/components/mdx/components/index.ts, apps/badass/src/components/mdx/components/team-members-block.tsx, apps/badass/src/components/mdx/index.tsx, apps/badass/src/components/navigation.tsx, apps/badass/src/lib/case-studies.ts, apps/badass/src/pages/articles.tsx, apps/badass/src/pages/partners/index.tsx, apps/badass/src/styles/mdx-components.css, apps/badass/studio/schemas/documents/caseStudy.js, apps/badass/tailwind.config.js
Epic React case study actually is not completed, this PR contains some mdx components for it + fixes for the rest of case studies (Dan's and Emma's). I will continue with ER case study in next PR.
<details>
<summary>Launch Epic React (wip)</summary>
</details>
P.S. Have to deploy Studio's changes after this get merged
=> Badass.dev: launch Epic React case study (wip) + fixes for existing cases

apps/colt-steele/src/pages/check-your-email.tsx, apps/colt-steele/src/pages/login.tsx, apps/colt-steele/src/styles/globals.css, apps/colt-steele/src/styles/login.css, apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/pages/brand.tsx, apps/epic-web/src/pages/check-your-email.tsx, apps/epic-web/src/pages/login.tsx, apps/epic-web/src/styles/globals.css, apps/epic-web/src/styles/login.css, apps/epic-web/tailwind.config.js, apps/protailwind/src/pages/check-your-email-copy.tsx, apps/protailwind/src/pages/login-copy.tsx, apps/protailwind/src/styles/globals.css, apps/protailwind/src/styles/login.css, apps/total-typescript/src/pages/check-your-email.tsx, apps/total-typescript/src/styles/globals.css, apps/total-typescript/src/styles/login.css, apps/total-typescript/tailwind.config.js, packages/create-skill-app/templates/next/.config-templates/globals.css, packages/create-skill-app/templates/next/src/pages/login.tsx, packages/create-skill-app/templates/next/src/styles/login.css, packages/skill-lesson/login/index.tsx
=> feat: unified login pages

apps/epic-web/src/components/app/layout.tsx, apps/epic-web/src/pages/full-stack-workshop-series-vol-1.tsx, packages/skill-api/src/core/services/stripe-checkout.ts, packages/skill-lesson/path-to-purchase/pricing.tsx
=> feat(skill-api): accept cancelUrl argument

apps/epic-web/src/pages/full-stack-workshop-series-vol-1.tsx, packages/commerce-server/src/format-prices-for-product.test.ts, packages/commerce-server/src/props-for-commerce.ts, packages/database/prisma/schema.prisma
=> feat(epic-web): stop selling when limit reached

apps/total-typescript/src/lib/tutorials.ts, apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/pages/rss.xml.ts
=> fix(tt): rss feed

apps/colt-steele/src/pages/creator/tips/new.tsx, apps/epic-web/src/pages/creator/tips/new.tsx
=> fix(creator): typo

apps/testing-javascript/src/components/playlist/playlist-item.tsx
=> feat(tjs): add tracking call to 'Start Workshop'

apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/pages/buy.tsx, apps/total-typescript/src/pages/products/index.tsx, apps/total-typescript/src/pages/workshops/index.tsx, apps/total-typescript/src/templates/exercise-template.tsx, packages/skill-lesson/lib/products.ts, packages/skill-lesson/path-to-purchase/pricing.tsx
=> feat(tt): tt standalone workshop

apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/pages/workshops/index.tsx, apps/total-typescript/src/templates/exercise-template.tsx
=> fixing purchase layover

apps/total-typescript/src/styles/shiki-twoslash.css
=> Fixed a strange css bug in shiki-twoslash

apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/styles/video/video-overlays.css, apps/total-typescript/src/templates/exercise-template.tsx, apps/total-typescript/src/trpc/routers/products.ts, packages/skill-lesson/schemas/module.ts, packages/skill-lesson/video/video-overlays.tsx
=> feat(tt): make buy overlay work for all products

apps/total-typescript/src/pages/products/[slug].tsx, apps/total-typescript/src/templates/product-template.tsx
=> feat(tt): ogImage for products

apps/total-typescript/src/lib/workshops.ts, apps/total-typescript/src/styles/pricing.css, apps/total-typescript/src/templates/workshop-template.tsx
=> feat(tt): default to bundle product in pricing widgets

packages/commerce-server/src/@types/index.ts, packages/commerce-server/src/format-prices-for-product.ts
=> fix(commerce-server): types

apps/testingaccessibility/src/pages/thanks/redeem.tsx
secondarily trying to test if these build errors on TA that popped up in another PR persist here as well:
https://vercel.com/skillrecordings/testingaccessibility-com/Gq3Dv5Lv2y6RKReo4oL6ftue46D3
=> types(ta): remove extra param type

packages/commerce-server/src/format-prices-for-product.ts, packages/skill-api/src/core/services/stripe-checkout.ts, packages/skill-lesson/path-to-purchase/pricing.tsx
=> corrects incorrect all region upgrade pricing

apps/total-typescript/src/styles/pricing.css, packages/skill-lesson/path-to-purchase/pricing.tsx
=> update(tt): less confusing team pricing presentation of purchased products

packages/commerce-server/src/format-prices-for-product.ts, packages/skill-lesson/path-to-purchase/pricing.tsx
I added a logic branch for PPP that looks to see if we are upgrading to a higher tier and **automatically applies PPP coupon** instead of requiring user intervention for this
=> add logic branch to price calculation

apps/badass/src/components/mdx/components/toc.tsx, apps/badass/src/lib/case-studies.ts, apps/badass/src/styles/fonts.css, apps/badass/src/styles/mdx-components.css
fixes for https://github.com/skillrecordings/products/pull/1094
before:
after:
=> badass.dev: fix font settings

apps/testing-javascript/next.config.js, apps/testing-javascript/src/components/lessons-sidebar.tsx, apps/testing-javascript/src/pages/index.tsx, apps/testing-javascript/src/templates/lesson-template.tsx
=> TJS: more tweaks for the Lesson page

apps/scriptkit/src/path-to-purchase-react/pricing.tsx, apps/scriptkit/src/team/buy-more-seats.tsx, apps/testing-javascript/src/path-to-purchase/pricing.tsx, apps/testingaccessibility/package.json, apps/testingaccessibility/src/components/pricing.tsx, apps/testingaccessibility/src/components/team/buy-more-seats.tsx, packages/skill-lesson/utils/build-stripe-checkout-path.test.ts, pnpm-lock.yaml
- feat(skill-lesson): add tests for path builder
- feat: use stripe checkout path builder everywhere
- feat: add missing applied merchant coupons
=> Add tests to stripe checkout path builder, use builder across other apps

packages/commerce-server/src/format-prices-for-product.test.ts, packages/commerce-server/src/format-prices-for-product.ts, packages/commerce-server/src/get-calculated-price.test.ts, packages/commerce-server/src/get-calculated-price.ts, packages/skill-api/src/core/services/stripe-checkout.ts
`getCalculatedPriced` --> `getCalculatedPrice`
=> fix(commerce-server): fix typo in function name

apps/testingaccessibility/next.config.js
=> fix(ta): transpile skill-lesson pkg

packages/skill-api/src/core/services/stripe-checkout.ts
Currently, the two labels that get applied are either "Unrestricted" or "Upgrade from <Product Name>". These don't quite cover two other scenarios though.
1. An upgrade to bundle where PPP is still applied, it could read something like, "Upgrade from Core Volume + PPP 65% off". This one is tricky because stripe doesn't let you apply multiple coupons, so we have to communicate both in a single coupon line item (with only 40 characters).
2. An upgrade that is both to Bundle and to remove the Region Restriction, so a label like "Unrestricted Upgrade from <Product Name>" would work.
Note: because Stripe restricts coupon names to being 40 characters or less and because our product names are sometimes a little long (e.g. `Total TypeScript Vol. 1`), we sometimes have to shave down the coupon …
=> feat(tt): improve coupon names for upgrades

apps/protailwind/next.config.js
=> feat(pt): Discord route redirect in next config

apps/total-typescript/src/templates/workshop-template.tsx, packages/skill-lesson/hooks/use-mux-player.tsx, packages/skill-lesson/trpc/routers/module-progress.ts, packages/skill-lesson/utils/get-next-section.ts, packages/skill-lesson/video/module-lesson-list/lesson-list.tsx, packages/skill-lesson/video/video-overlays.tsx
=> fix(tt): improve empty section awareness

apps/total-typescript/src/certificate/certificate-form.tsx, apps/total-typescript/src/certificate/module-certificate.tsx, apps/total-typescript/src/templates/tutorial-template.tsx, apps/total-typescript/src/templates/workshop-template.tsx, apps/total-typescript/tailwind.config.js
=> feat(tt): add certificates for free tutorials

packages/database/src/prisma-api.ts, packages/skill-lesson/trpc/routers/progress.ts
=> fix(db): stop writing duplicate lesson progress

apps/total-typescript/src/pages/transfer/[purchaseUserTransferId].tsx
If we detect that the current user doesn't match the _target_ user of a
Transfer Request, then we display a message saying as much and guide
them to sign in to the correct account before Accepting.
If the currently signed in user is someone other than the target of the Transfer Request, e.g. the source of the request, then display this message:
Once they have signed into the correct account, when they revisit the link, they will see the Accept Transfer button.
=> feat(tt): help transfer user w/ wrong acct

apps/epic-web/src/pages/api/video-thumb.ts, apps/epic-web/src/pages/tutorials/[module]/[section]/[lesson]/embed.tsx
this checks for user abilities in `GetServerSideProps` and passes them as `initialData` to TRPC query which then revalidates when user logs in or out.
=> feat(ew): fetch initial video embed data and abilities in GSSP and then revalidate with TRPC

apps/epic-web/src/pages/tutorials/[module]/[section]/[lesson]/embed.tsx, packages/skill-lesson/hooks/use-video-resource.tsx, packages/skill-lesson/trpc/routers/modules.ts, packages/skill-lesson/trpc/routers/video-resource.ts, packages/skill-lesson/utils/define-resource-ability-rules.ts
=> refactor(sl): check user ability before loading full video resource

apps/total-typescript/src/pages/products/index.tsx
This was pointing to /workshops/ instead of /bonuses/
=> Fixed a broken link on the products page

apps/badass/src/components/card.tsx, apps/badass/src/components/mdx/components/introduce-card.tsx, apps/badass/src/components/navigation.tsx, apps/badass/src/lib/articles.ts, apps/badass/src/pages/articles.tsx, apps/badass/src/pages/index.tsx, apps/badass/src/pages/partners/index.tsx, apps/badass/studio/schemas/documents/article.js
**Case Studies page:**
<details>
<summary>1440px:</summary>
</details>
<details>
<summary>1024px:</summary>
</details>
<details>
<summary>768px:</summary>
</details>
<details>
<summary>390px:</summary>
</details>
**Articles page:**
<details>
<summary>1440px:</summary>
</details>
<details>
<summary>1024px:</summary>
</details>
<details>
<summary>768px:</summary>
</details>
<details>
<summary>390px:</summary>
</details>
Need to compile and add descriptions to some of the articles.
=> badass.dev: reworked Case Studies and Articles pages

apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/lib/workshops.ts, apps/epic-web/src/pages/index.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/embed.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/exercise.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/index.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/solution.tsx, apps/epic-web/src/pages/workshops/[module]/completed.tsx, apps/epic-web/src/pages/workshops/[module]/index.tsx, apps/epic-web/src/pages/workshops/index.tsx, apps/epic-web/src/styles/commerce.css, apps/epic-web/src/styles/video/lesson-title.css, apps/epic-web/src/styles/video/module-lesson-list.css, apps/epic-web/src/styles/video/video-overlays.css, apps/epic-web/src/templates/exercise-template.tsx, apps/epic-web/src/templates/tutorial-template.tsx, apps/epic-web/src/templates/workshop-template.tsx, apps/total-typescript/src/templates/exercise-template.tsx, packages/skill-lesson/path-to-purchase/pricing.tsx
implements workshop pages along with video embeds.
=> feat(ew): add workshops

apps/total-typescript/src/components/mdx/index.tsx, apps/total-typescript/src/pages/concepts/[slug]/index.tsx, apps/total-typescript/src/templates/article-template.tsx
=> feat(tt): linked headings

apps/total-typescript/src/components/mdx/index.tsx
=> fix(tt): linked headings with multiple hashes

apps/colt-steele/src/styles/video/video-overlays.css, apps/epic-web/src/styles/video/video-overlays.css, apps/pro-nextjs/src/styles/video/video-overlays.css, apps/protailwind/src/styles/video/video-overlays.css, apps/total-typescript/src/styles/video/video-overlays.css, apps/total-typescript/src/templates/exercise-template.tsx, packages/skill-lesson/hooks/use-mux-player.tsx, packages/skill-lesson/video/video-overlays.tsx, packages/skill-lesson/video/video.tsx
=> feat(overlays): display module progress

apps/badass/src/pages/articles.tsx, apps/badass/src/pages/partners/index.tsx, apps/badass/src/templates/article-template.tsx, apps/badass/src/templates/case-study-template.tsx
Update Article and Case Study templates with new Subscribe form.
=> badass.dev: update Article and Case Study templates with new Subscribe form

apps/testing-javascript/src/components/landing/access-your-course.tsx, apps/testing-javascript/src/pages/index.tsx, apps/testing-javascript/src/server/products.server.ts, apps/testing-javascript/src/templates/landing-template.tsx
This PR adds some logic to check that the `LessonProgress` records for the user align with all of the lessons. If so, then we display the 'Download Course Completion Certificate' button.
=> feat(tjs): check completion for Certificate button

apps/testing-javascript/src/components/navigation.tsx
This adds the 'Invite team' link for team owners to both the desktop and mobile navs.
=> feat(tjs): link to team page from nav bar

apps/total-typescript/package.json, apps/total-typescript/src/certificate/certificate-form.tsx, apps/total-typescript/src/trpc/routers/_app.ts, apps/total-typescript/src/trpc/routers/certificate.ts, apps/total-typescript/src/utils/cloudinary.ts, pnpm-lock.yaml
https://github.com/skillrecordings/products/assets/25487857/fbe97b96-bb31-41bf-9022-5d3f385bd641
=> feat(tt): make completion certificate a permalink to cached image

apps/total-typescript/schemas/documents/videoResource.ts, apps/total-typescript/schemas/index.ts, apps/total-typescript/schemas/objects/transcript.tsx
=> feat(tt): adding transcript in the schema

apps/epic-web/src/components/app/navigation.tsx, packages/skill-lesson/lib/products.ts, packages/skill-lesson/trpc/routers/purchases.ts
=> feat(ew): invite team link

apps/epic-web/package.json, apps/epic-web/src/components/app/footer.tsx, apps/epic-web/src/components/app/layout.tsx, apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/components/contact/contact-email-field.tsx, apps/epic-web/src/components/contact/contact-form.tsx, apps/epic-web/src/pages/_app.tsx, apps/epic-web/src/pages/contact.tsx, apps/epic-web/src/styles/feedback-widget.css, apps/epic-web/src/styles/globals.css, pnpm-lock.yaml
=> feat(ew): contact page

apps/testing-javascript/src/components/pricing-section.tsx, apps/testing-javascript/src/path-to-purchase/pricing.tsx, apps/testing-javascript/src/styles/pricing.css
The tiers that are lower than purchased one are gray-out and not available for purchase now.
=> TJS: tweak pricing component

apps/epic-web/schemas/documents/module.tsx
=> updating epic web schema to support lesson in module

apps/testing-javascript/src/path-to-purchase/pricing.tsx
=> feat(tjs): styles for "credit applied" message

apps/epic-web/src/pages/faq.mdx, apps/epic-web/src/pages/faq.tsx
=> Add Epic Web FAQ

apps/epic-web/schemas/deskStructure.ts, apps/epic-web/schemas/documents/interview.ts, apps/epic-web/schemas/documents/module.tsx, apps/epic-web/schemas/index.ts, apps/epic-web/schemas/structure/bonuses.js, apps/epic-web/schemas/structure/interviews.js, apps/epic-web/src/lib/bonuses.ts, apps/epic-web/src/pages/workshops/index.tsx, packages/skill-lesson/lib/products.ts, packages/skill-lesson/path-to-purchase/pricing.tsx
=> feat(ew): add schemas for bonuses & interviews

apps/epic-web/src/pages/faq.tsx
=> ewd: update faq.tsx

apps/epic-web/src/pages/index.tsx, apps/epic-web/src/pages/workshops/index.tsx, apps/epic-web/src/templates/purchased-product-template.tsx, packages/commerce-server/src/@types/index.ts, packages/commerce-server/src/props-for-commerce.ts
=> update(ewd): list bonuses

apps/epic-web/src/pages/activate/success.tsx
=> chore(ew): fix typo

packages/commerce-server/src/@types/index.ts, packages/commerce-server/src/format-prices-for-product.ts, packages/commerce-server/src/get-active-merchant-coupon.ts, packages/commerce-server/src/record-new-purchase.ts, packages/database/src/prisma-api.ts, packages/skill-api/src/core/services/stripe-checkout.ts, packages/skill-lesson/path-to-purchase/pricing.tsx, packages/skill-lesson/trpc/routers/pricing.ts, packages/skill-lesson/utils/build-stripe-checkout-path.ts
=> record the coupon that got used

apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/components/workshop-app.tsx, apps/epic-web/src/emails/lesson-complete-email.tsx, apps/epic-web/src/pages/bonuses/index.tsx, apps/epic-web/src/pages/workshops/index.tsx, apps/epic-web/src/templates/exercise-template.tsx
Thank you all so much for Epic Web 🚀 
As a small thank you, I figured I'd fix a few typos I've found while completing the lessons!
=> chore: typos

apps/epic-web/src/components/landing-copy.mdx
Closes https://github.com/epicweb-dev/kcdshop/issues/154
=> fix(ewd): fix landing copy typo

apps/epic-web/src/pages/thanks/purchase.tsx
=> ew-93 allow user to transfer on thanks screen

apps/epic-web/src/pages/profile.tsx
this fixes prop according to component's props type
=> feat(ew): fix ts error

packages/database/src/prisma-api.ts
=> feat(ew): ensure best default coupon is picked

apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/lib/workshops.ts, apps/epic-web/src/pages/get-started/index.tsx, packages/skill-lesson/video/video-overlays.tsx, packages/skill-lesson/video/video.tsx
I adjusted copy, CTA, and added walkthrough video along with module aware cuePoints with relevant links.
https://github.com/skillrecordings/products/assets/25487857/e00de642-0001-45e9-981f-6737bdb1939d
=> feat(ewd): improved exercise overlay cta

apps/epic-web/src/pages/boss.tsx
=> fix(ewd): add padding to boss letter

apps/epic-web/src/pages/workshops/index.tsx
=> fix(ewd): wrong lesson count display

apps/epic-web/src/pages/api/certificate/index.ts
=> fix(ewd): certificates

apps/epic-web/src/pages/articles.tsx
=> fix(ewd): add object-cover to article images

apps/epic-web/src/components/app/layout.tsx, apps/epic-web/src/components/app/navigation.tsx
=> feat(ewd): global sale banner

apps/testing-javascript/package.json, pnpm-lock.yaml
=> fix(tjs): sanity deploy needs autoprefixer

apps/badass/src/styles/mdx-components.css
<details>
</details>
<details>
</details>
=> feat(badass.dev): fix styles

apps/testing-javascript/package.json, apps/testing-javascript/sanity.config.ts, pnpm-lock.yaml
=> feat(tjs): add Sanity markdown plugin

apps/testing-javascript/schemas/documents/module.jsx
=> feat(tjs): add Bonus as module type for interviews

apps/testing-javascript/src/templates/lesson-template.tsx
=> feat(tjs): display body description as markdown

packages/database/src/prisma-api.ts
@nicollguarnizo and I paired on this. We've manually tested that this works for restricted and unrestricted coupons. We're looking into writing some automated tests for this, but will probably save that for a follow-up PR.
=> feat(tt): apply unrestricted default coupon to all

apps/epic-web/src/pages/api/og/index.tsx, apps/epic-web/src/templates/exercise-template.tsx, apps/epic-web/src/templates/tip-template.tsx, apps/epic-web/src/utils/get-og-image.ts
=> feat(ewd): improved share cards for lesson pages

apps/epic-web/src/lib/articles.ts
Instead of throwing a ZodError when parsing fails, this results in a
null that the call sites expect in order to render a 404.
I noticed a ton of these Zod errors in Sentry and in the Vercel logs. A lot of this is due to lookups of non-existent articles (unknown slugs) or bots trying to access random endpoints (e.g. `epicweb.dev/abcdefc.something.css`) or even things like `epicweb.dev/apple-touch-icon-precomposed.png`.
=> feat(ew): return null for unfound article

apps/epic-web/seed_data/Product.00001.sql
=> add seed data for new products EW

apps/epic-web/src/templates/workshop-template.tsx
=> moving bundle higher

apps/epic-web/src/styles/commerce.css, packages/skill-lesson/lib/pricing.ts
=> style(ewd): features icons in pricing

apps/testing-javascript/.env.production
=> fix: NEXTAUTH_URL has to match app URL exactly

apps/epic-web/src/styles/video/video-overlays.css, packages/skill-lesson/video/video-overlays.tsx, packages/ui/primitives/progress.tsx
=> fix(ewd): progress bars

apps/total-typescript/src/offer/survey/survey-popup.tsx
=> style(tt): hide survey in print (invoices)

apps/epic-web/src/components/author-bio.tsx, apps/epic-web/src/components/primary-newsletter-cta.tsx, apps/epic-web/src/pages/index.tsx, apps/epic-web/src/pages/newsletter.tsx
=> feat(ewd): dynamic cta on hp

apps/epic-web/src/lib/products.ts, apps/epic-web/src/pages/events/[event].tsx, apps/epic-web/src/pages/products/index.tsx, apps/epic-web/src/styles/commerce.css, apps/epic-web/src/styles/globals.css, apps/epic-web/src/templates/event-template.tsx, apps/epic-web/src/templates/purchased-product-template.tsx, packages/commerce-server/src/@types/index.ts, packages/skill-lesson/path-to-purchase/products.server.ts
=> feat(ewd): polish event template & purchase flow

apps/epic-web/src/components/app/layout.tsx, apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/hooks/use-global-banner.ts, apps/epic-web/src/pages/events/[event].tsx, apps/epic-web/src/templates/exercise-template.tsx, packages/skill-lesson/trpc/routers/products.ts
=> feat(ewd): setup global banner for live events

apps/epic-react/schemas/documents/module.tsx
=> fix: un-break the workshop preview images

apps/epic-web/src/lib/talks.ts, apps/epic-web/src/pages/talks/index.tsx, apps/epic-web/src/templates/talk-template.tsx
=> feat(ew): adding authors to talks

apps/epic-web/src/pages/talks/index.tsx
=> updates metadata

packages/commerce-server/src/get-coupon-for-code.ts, packages/commerce-server/src/props-for-commerce.ts, packages/commerce-server/src/validate-coupon.test.ts, packages/commerce-server/src/validate-coupon.ts, pnpm-lock.yaml
=> feat: enforce product id restrictions for coupons

apps/epic-web/src/styles/commerce.css, apps/epic-web/src/templates/event-template.tsx, packages/skill-lesson/hooks/use-convertkit.tsx, packages/skill-lesson/path-to-purchase/pricing.tsx, packages/skill-lesson/path-to-purchase/products.server.ts, packages/skill-lesson/trpc/routers/convertkit.ts
=> feat(ewd): event waitlist

apps/epic-web/src/pages/events/index.tsx
=> sposts -> spots

apps/devrel-fyi/src/templates/lesson-template.tsx, apps/epic-react/src/templates/lesson-template.tsx, apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/templates/exercise-template.tsx, apps/epic-web/src/trpc/routers/module-resources.ts, apps/epic-web/tsconfig.json, apps/pro-aws/src/templates/lesson-template.tsx, apps/pro-nextjs/src/components/exercise-overlay.tsx, apps/pro-nextjs/src/templates/exercise-template.tsx, packages/create-skill-app/templates/next/src/templates/lesson-template.tsx
I noticed one of these and then did a search and found several of them.
Not sure how this code isn't breaking. When I try to run a minimal repro
in node, it errors.
=> fix: remove errant exclamation point

apps/epic-web/src/pages/creator/tips/new.tsx
=> Spelling fix: tile -> title

apps/epic-web/src/pages/conf/index.tsx
=> Link Park City and the live stream

apps/epic-web/src/templates/event-template.tsx
=> display times in PST

apps/epic-react/src/lib/workshops.ts
this is a proof-of-concept for how we can fetch only the modules that belong to a specific product. this is the kind of thing we could call server-side after looking up the purchased product ID of the current user.
=> feat(er): fetch modules by product id

apps/badass/package.json, apps/colt-steele/package.json, apps/devrel-fyi/package.json, apps/epic-react/package.json, apps/epic-web/package.json, apps/pro-aws/package.json, apps/pro-nextjs/package.json, apps/skill-stack-docs/package.json, apps/testing-javascript/package.json, apps/total-typescript/package.json, packages/create-skill-app/templates/next/.config-templates/package-template.json, packages/skill-lesson/package.json, packages/ui/package.json, pnpm-lock.yaml
=> chore: upgrade tailwind

apps/badass/src/components/buttons.tsx, apps/badass/src/components/card.tsx, apps/badass/src/components/landing/articles.tsx, apps/badass/src/components/mdx/components/fancy-title-with-subtitle.tsx, apps/badass/src/components/mdx/components/full-transcript.tsx, apps/badass/src/components/mdx/components/index.ts, apps/badass/src/components/mdx/index.tsx, apps/badass/src/lib/articles.ts, apps/badass/src/styles/mdx-components.css, apps/badass/src/templates/article-template.tsx, apps/badass/tailwind.config.js
After this PR gets merged I'll push the next one that will clean up Sanity from unused fields.
Live preview: https://badass-turbo-88xkimtdx-skillrecordings.vercel.app/articles
=> feat(badass): markdown for the Articles

apps/badass/src/components/mdx/components/index.ts, apps/badass/src/components/mdx/components/resources-links.tsx, apps/badass/src/components/mdx/index.tsx, apps/badass/src/components/podcast-parallax-images.tsx, apps/badass/src/lib/case-studies.ts, apps/badass/src/pages/podcast/[podcastSeason]/[podcastEpisode].tsx, apps/badass/src/pages/podcast/[podcastSeason]/index.tsx, apps/badass/src/styles/mdx-components.css, apps/badass/src/templates/case-study-template.tsx, apps/badass/src/templates/podcast-episode-template.tsx
This refactors and applies updated design of Podcast page:
Live preview: https://badass-turbo-jnw8yhjuw-skillrecordings.vercel.app/podcast/course-builders/effectively-using-learner-feedback-with-marie-poulin
**Before:**
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Tablet</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
**After:**
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Tablet</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
=> refactor(badass): reworked Podcast page

apps/badass/src/components/call-to-action-form.tsx, apps/badass/src/styles/globals.css, apps/badass/src/styles/subscribe-form.css, packages/skill-lesson/convertkit/convertkit-subscribe-form.tsx, packages/skill-lesson/hooks/use-convertkit-form.ts
This adds ability to pass custom `yup` schema to `SubscribeToConvertkitForm`.
Used this to implement custom styles for the subscribe form at badass.dev
=> feat(badass): form validation styling

packages/database/prisma/schema.prisma
https://app.planetscale.com/skill-recordings/kcd-products/insights/recommendations/2
TODO: Set up the Deploy Requests on PlanetScale
=> feat(ew): add index to Purchase.userId

packages/skill-api/src/core/services/process-stripe-webhook.ts
=> fix(tjs): stringify logged object

apps/testing-javascript/src/components/landing/access-your-course.tsx
=> fix(tjs): use correct playback ID for Update video

apps/total-typescript/src/app/book/[chapter]/[resource]/(lesson)/page.tsx, apps/total-typescript/src/app/book/_components/challenge.tsx, apps/total-typescript/src/app/book/_components/chapters-index.tsx, apps/total-typescript/src/app/book/_schema/book-schemas.ts, apps/total-typescript/src/app/book/page.tsx, apps/total-typescript/src/lib/book.ts, apps/total-typescript/src/lib/videos.ts
https://www.loom.com/share/2dc5af54501d4769905a603f5289c8ed?sid=4966b862-03bb-48d1-be8d-7cef1673ab24
=> chore: rework rsc structure for book chapters

apps/epic-web/schemas/documents/article.tsx, apps/epic-web/schemas/documents/contributor.tsx, apps/epic-web/schemas/documents/event.tsx, apps/epic-web/schemas/documents/module.tsx, apps/epic-web/schemas/documents/talk.ts, apps/epic-web/schemas/documents/tip.ts, apps/epic-web/schemas/index.ts, apps/epic-web/schemas/objects/contributors.tsx, apps/epic-web/src/lib/articles.ts, apps/epic-web/src/lib/contributors.ts, apps/epic-web/src/lib/events.ts, apps/epic-web/src/lib/talks.ts, apps/epic-web/src/lib/tips.ts, apps/epic-web/src/lib/tutorials.ts, apps/epic-web/src/lib/workshops.ts, apps/epic-web/src/pages/articles.tsx, apps/epic-web/src/pages/talks/index.tsx, apps/epic-web/src/pages/tips/index.tsx, apps/epic-web/src/pages/tutorials/index.tsx, apps/epic-web/src/templates/talk-template.tsx, apps/epic-web/src/templates/tip-template.tsx, apps/epic-web/src/templates/tutorial-template.tsx
=> refactor(ewd): authors are contributors with a role

apps/epic-react/src/styles/commerce.css
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> styles(er-next): adjust styles for the Pricing component

apps/testing-javascript/src/middleware.ts, apps/testing-javascript/src/pages/admin/index.tsx, apps/testing-javascript/src/server/get-middleware-response.ts, apps/testing-javascript/src/server/rewrite-next-response-to-path.ts, apps/total-typescript/src/middleware.ts
=> feat: coupon admin for testing js

apps/epic-react/src/components/video-overlays/blocked-overlay.tsx, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/styles/globals.css, apps/epic-react/src/styles/lesson-completion-toggle.css, apps/epic-react/src/templates/__lesson-template.tsx, apps/epic-react/src/templates/lesson-template.tsx, packages/skill-lesson/video/video.tsx
This is the very first pass:
- general markup including theater mode toggle
- custom blocked overlay
=> feat(er-next): Lesson page rework - iteration#1

apps/epic-react/src/templates/lesson-template.tsx
=> fix: remove these lines, dead code

apps/epic-react/src/styles/globals.css, apps/epic-react/src/templates/lesson-template.tsx
This casts Lessons List as close as possible to how it looks at original ER.
<details>
<summary>Lessons List:</summary>
</details>
=> feat(er-next): Lessons List

apps/epic-react/src/components/podcasts/podcast-player.tsx
https://github.com/skillrecordings/products/assets/6188161/ad569403-7be9-4491-8efe-c24bc31666b7
https://github.com/skillrecordings/products/assets/6188161/06072c43-2c72-4339-865d-b08146177725
=> add episodeId to dependency array to update podcast player url

packages/database/README.md
=> feat(db): add README to the database package

apps/epic-react/src/components/app/navigation/index.tsx
=> feat(ER): add Module link to nav

packages/skill-lesson/lib/module-progress.ts
=> store moduleCompletedAt as string not date

apps/epic-web/schemas/documents/talk.ts
=> feat(ewd): ability to assign one-time contributor to a talk

apps/epic-web/src/components/resource-contributor.tsx, apps/epic-web/src/lib/talks.ts, apps/epic-web/src/pages/talks/index.tsx, apps/epic-web/src/templates/talk-template.tsx
=> feat(ew): display one time contributor talks epic web

apps/epic-web/src/components/app/footer.tsx, apps/epic-web/src/lib/events.ts, apps/epic-web/src/pages/events/index.tsx
=> feat(ew): add conf to footer and events page

apps/total-typescript/src/templates/product-template.tsx
Fixes bug introduced in https://github.com/skillrecordings/products/pull/1517
=> fix(tt): wrap Pricing in Price Check provider

apps/epic-react/src/styles/commerce.css
<details>
<summary>Before</summary>
</details>
<details>
<summary>After (dark)</summary>
</details>
<details>
<summary>After (light)</summary>
</details>
=> fix(er-next): styles for PPP

apps/epic-react/src/components/fancy-button.tsx, apps/epic-react/src/components/subscribe-react-email-course-cta.tsx, apps/epic-react/src/config.ts, apps/epic-react/src/pages/invoices/index.tsx, apps/epic-react/src/pages/welcome.tsx, apps/epic-react/src/styles/globals.css, apps/epic-react/src/styles/team.css
<details>
<summary>Individual</summary>
</details>
<details>
<summary>Individual (dark)</summary>
</details>
<details>
<summary>Team</summary>
</details>
<details>
<summary>Team (dark)</summary>
</details>
=> feat(ER-next): welcome page for post purchase magic link callback

apps/epic-react/src/components/app/navigation/index.tsx, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/index.tsx, apps/epic-react/src/pages/learn.tsx, apps/epic-react/tailwind.config.js
- applies `shouldReduceMotion` for the animation on the Landing page
- Github repo link under each module on the `Learn` page
- fix markdown styles on the `Lesson` page
- minor clean up's
=> fix(er-next): miscellaneous tweaks and clean up

apps/epic-react/src/pages/learn.tsx, apps/epic-react/src/pages/modules/[module]/completed.tsx
<details>
</details>
<details>
</details>
=> refactor(er-next): no certificate for the Welcome module

apps/epic-react/src/components/app/footer.tsx, apps/epic-react/src/components/app/navigation/index.tsx, apps/epic-react/src/components/app/navigation/mobile-navigation.tsx, apps/epic-react/src/components/landing/interviews.tsx, apps/epic-react/src/components/landing/intro-tour-video.tsx, apps/epic-react/src/components/landing/testimonials.tsx, apps/epic-react/src/components/welcome-banner.tsx, apps/epic-react/src/pages/learn.tsx, apps/epic-react/src/styles/commerce.css
this fixes:
- Welcome banner is no more shown for non-paid users
- KCD DIscord --> Epic Web Discord
- tweak the styles for mobile menu, pricing component
=> fix(er-next): fix Welcome banner

apps/epic-react/.env.development, apps/epic-react/.env.production, apps/epic-react/package.json, apps/epic-react/process.d.ts, apps/epic-react/src/@types/js-yaml.d.ts, apps/epic-react/src/inngest/functions/stripe/checkout-completed.ts, apps/epic-react/src/inngest/functions/stripe/webhook-received.ts, apps/epic-react/src/inngest/inngest.config.ts, apps/epic-react/src/inngest/inngest.server.ts, apps/epic-react/src/pages/api/cron.ts, apps/epic-react/src/pages/api/inngest.ts, apps/epic-react/src/vercel.json, pnpm-lock.yaml
`/thanks/purchase` throws a 404 because inngest functions are not set up correctly for epic react. This adds that set up, when merged we will need to add this app in the inngest dashboard
=> (Epic React Next) set up inngest

apps/epic-react/src/inngest/inngest.config.ts
=> feat(epic react next) add stripe inngest functions to app

apps/total-typescript/src/pages/books/[book]/[chapter]/index.tsx, packages/skill-lesson/markdown/shiki-twoslash-plugin.ts
=> chore(tt): dont throw when encountered twoslash error and let the build proceed

apps/total-typescript/src/pages/books/[book]/[chapter]/index.tsx, apps/total-typescript/src/styles/video/module-lesson-list.css, apps/total-typescript/src/templates/exercise-template.tsx
=> style(tt): do not display exercise as nested resource in module collection list

apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/components/cta/resource-cta.tsx, apps/epic-web/src/templates/article-template.tsx, apps/epic-web/src/templates/exercise-template.tsx, apps/epic-web/src/templates/talk-template.tsx, apps/epic-web/src/templates/tip-template.tsx, apps/epic-web/src/trpc/routers/_app.ts, apps/epic-web/src/trpc/routers/cta.ts
=> feat(ewd): resource CTA router spike

packages/skill-lesson/video/module-lesson-list/lesson-list.tsx
=> fix(tt): section scroll overflow in module lesson list

apps/total-typescript/src/lib/exercises.ts, apps/total-typescript/src/pages/api/video-thumb.ts, apps/total-typescript/src/pages/books/[book]/[chapter]/index.tsx, apps/total-typescript/src/trpc/routers/_app.ts, apps/total-typescript/src/trpc/routers/exercises.ts
=> feat(tt): book CTA for inline exercise to corresponding Pro video

apps/total-typescript/src/components/exercise-overlay.tsx, apps/total-typescript/src/exercise/local-dev-prefs/dialog.tsx, apps/total-typescript/src/exercise/local-dev-prefs/form.tsx, apps/total-typescript/src/lib/user-prefs.ts, apps/total-typescript/src/pages/books/[book]/[chapter]/index.tsx, packages/skill-lesson/schemas/module.ts
=> feat(tt): update overlay

apps/total-typescript/src/pages/api/og/og-product.tsx, apps/total-typescript/src/templates/product-template.tsx, apps/total-typescript/src/templates/purchased-product-template.tsx
=> feat(tt): dynamic product og image

apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/solution/embed.tsx, apps/epic-web/src/templates/embed-template.tsx, apps/epic-web/src/utils/get-props-for-embeds.ts
=> fix(ew): EW-136 Solution Embed Fails with API error

apps/total-typescript/migrations/book-chapters-into-chapter-resources.ts, apps/total-typescript/src/components/book/bookmarkable-markdown-heading.tsx, apps/total-typescript/src/lib/book.ts, apps/total-typescript/src/pages/books/[book]/[chapter]/index.tsx, apps/total-typescript/src/pages/search.tsx, apps/total-typescript/src/search-bar/index.tsx, apps/total-typescript/src/templates/book-chapter-template.tsx, apps/total-typescript/src/trpc/routers/search.ts, apps/total-typescript/src/utils/extract-markdown-headings.ts
=> feat(tt): use chapterResources for rendering book contents and surface them in search

apps/total-typescript/src/components/landing-copy.mdx
=> update landing page tt

apps/epic-react/package.json, apps/epic-react/src/components/mdx-components/code.tsx, apps/epic-react/src/components/mdx-components/index.tsx, apps/epic-react/src/pages/_app.tsx, pnpm-lock.yaml
<details>
<summary>Code highlighting</summary>
</details>
=> feat(EW): implement code highlighting

apps/total-typescript/src/components/landing-copy.mdx
Updates homepage blurb for TTS Pro Essentials
=> Update TTS Pro Essentials blurb

apps/epic-react/src/pages/api/video-thumb.ts
=> fix(ER-next): fix broken video thumbnails

apps/epic-react/src/pages/api/video-thumb.ts, apps/epic-react/src/templates/lesson-template.tsx, packages/skill-lesson/utils/get-base-url.ts
=> fix(ER-next): test of the fix

apps/epic-react/src/components/app/navigation/feedback-button.tsx, apps/epic-react/src/components/app/navigation/logout-button.tsx, apps/epic-react/src/components/app/navigation/theme-toggle.tsx
=> fix(ER-next): fix tooltips delay

apps/total-typescript/src/exercise/stackblitz-iframe.tsx
I've enabled the section repos strategy (#1606) in the React repo, so time to enable it here.
=> Applied Stackblitz fix to react TS workshop

apps/total-typescript/src/components/book/book-exercise-embed.tsx, apps/total-typescript/src/components/exercise-overlay.tsx
=> update(tt): jetbrains exercise url structure

apps/epic-react/src/pages/welcome.tsx
=> fix(ER-next): fix link to the first lesson on the Welcome page

apps/devrel-fyi/src/pages/products/[slug].tsx, apps/devrel-fyi/src/pages/thanks/purchase.tsx, apps/epic-react/src/pages/products/[slug].tsx, apps/epic-react/src/pages/thanks/purchase.tsx, apps/epic-web/src/pages/products/[slug].tsx, apps/epic-web/src/pages/thanks/purchase.tsx, apps/epic-web/src/purchase-details/purchase-details-template.tsx, apps/pro-aws/src/pages/products/[slug].tsx, apps/testing-javascript/src/pages/team/index.tsx, apps/testing-javascript/src/purchase-details/purchase-details-template.tsx, apps/total-typescript/src/pages/products/[slug].tsx, apps/total-typescript/src/pages/team/index.tsx, apps/total-typescript/src/pages/thanks/purchase.tsx, apps/total-typescript/src/purchase-details/purchase-details-template.tsx, packages/database/src/prisma-api.ts, packages/skill-lesson/package.json, packages/skill-lesson/team/copy-invite-link.tsx, packages/skill-lesson/team/index.tsx, pnpm-lock.yaml
=> fix: update link for claiming inactive products

apps/epic-web/schemas/documents/event.tsx, apps/epic-web/src/lib/events.ts, apps/epic-web/src/templates/event-template.tsx
=> feat(ewd): self-paced workshop cta on past live events

apps/epic-web/src/templates/product-template.tsx
=> feat(ew): allow golden ticket claim in products/slug

apps/epic-web/src/emails/pixel-perfect-workshop-welcome-email.tsx, apps/epic-web/src/inngest/functions/post-purchase-automation/send-welcome-email.ts, apps/epic-web/src/inngest/inngest.config.ts
=> feat(ew): create post-purchased sequence 

apps/epic-react/src/pages/invoices/[merchantChargeId].tsx, apps/epic-react/src/pages/team/index.tsx, apps/epic-react/src/styles/team.css
<details>
<summary>Mobile</summary>
</details>
<details>
<summary>Desktop</summary>
</details>
=> style(ER-next): styles for the /team page

apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/embed.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/solution/embed.tsx, apps/epic-web/src/templates/embed-template.tsx, apps/epic-web/src/utils/get-props-for-embeds.ts
=> feat(ewd): product specific embed CTAs

apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/hooks/use-global-banner.ts, apps/epic-web/src/trpc/routers/cta.ts
=> feat(ewd): skip past events in CTAs and use the new router for global banner

apps/epic-react/next.config.js
The original epicreact.dev had these URL redirects so this one should too
=> feat(erd): add short url redirects

apps/epic-web/src/pages/camp/index.tsx
=> fix(ewd): update details for camp

apps/epic-web/src/hooks/use-golden-ticket.tsx, packages/skill-lesson/path-to-purchase/products.server.ts
=> fix: add instructors to golden ticket redeemer

apps/epic-react/src/pages/invoices/index.tsx, apps/epic-react/src/pages/learn.tsx, apps/epic-web/src/pages/invoices/index.tsx
=> fix(erv1): link to correct invoice for product

apps/total-typescript/src/pages/typescript-learning-path.tsx
=> update learning path

apps/total-typescript/src/pages/ts-reset/index.tsx
=> fix(tt): bug causing content on ts-reset page not showing with reduce motion enabled

apps/epic-react/src/lib/tutorials.ts
=> fix(er): fix the ogImage link for tutorials

apps/epic-react/src/lib/bonuses.ts
=> fix(erv1): the bonus module didn't have the workshop property

apps/epic-react/src/styles/globals.css, apps/epic-react/src/templates/exercise-template.tsx
https://github.com/user-attachments/assets/10176378-0615-469c-ad24-d66c7efd76fd
=> fix(er): fix navigation hover

apps/epic-web/src/emails/post-purchase-welcome-email.tsx, apps/epic-web/src/inngest/functions/post-purchase-automation/send-welcome-email.ts
@joelhooks You are right about the array type for `product`, this fixes that - https://github.com/skillrecordings/products/pull/1653#discussion_r1700723844
=> fix(ew): fixing the type for product

apps/epic-react/schemas/deskStructure.ts, apps/epic-react/schemas/documents/module.tsx, apps/epic-react/schemas/structure/legacy-modules.js, apps/epic-react/src/components/video-overlays/blocked-overlay.tsx, apps/epic-react/src/lib/legacy-modules.ts, apps/epic-react/src/pages/learn.tsx, apps/epic-react/src/pages/modules/[module]/[lesson]/index.tsx, apps/epic-react/src/pages/modules/[module]/[lesson]/solution/embed.tsx, apps/epic-react/src/pages/modules/[module]/[lesson]/solution/index.tsx, apps/epic-react/src/pages/modules/[module]/completed.tsx, apps/epic-react/src/pages/welcome.tsx, apps/epic-react/src/templates/exercise-template.tsx, apps/epic-react/src/utils/get-props-for-embeds.ts, packages/commerce-server/src/@types/index.ts
=> chore: migrate `workshop` to `legacy-module`

apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/workshops/[module]/[lesson]/embed.tsx, apps/epic-react/src/pages/workshops/[module]/[lesson]/exercise.tsx, apps/epic-react/src/pages/workshops/[module]/[lesson]/index.tsx, apps/epic-react/src/pages/workshops/[module]/[lesson]/solution/embed.tsx, apps/epic-react/src/pages/workshops/[module]/[lesson]/solution/index.tsx, apps/epic-react/src/pages/workshops/[module]/completed.tsx, apps/epic-react/src/pages/workshops/[module]/index.tsx, apps/epic-react/src/pages/workshops/index.tsx, apps/epic-react/src/templates/exercise-template.tsx, apps/epic-react/src/templates/workshop-template.tsx
=> feat: navigate to epic react v2 `/workshops`

apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/lib/workshops.ts, apps/epic-web/src/pages/get-started/index.tsx
=> fix(ewd): dynamic workshops list on get-started page

apps/epic-web/src/templates/tutorial-template.tsx
=> fix(ewd): fix completed tutorial cta

apps/epic-web/src/components/exercise-overlay.tsx
=> feat(ewd): more dynamic workshop app video poster in exercise overlays

apps/total-typescript/src/pages/invoices/[merchantChargeId].tsx
=> feat(tt): support newlines in textarea on invoices

apps/epic-react/src/components/exercise-overlay.tsx, apps/epic-react/src/lib/tutorials.ts, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/get-started/index.tsx, apps/epic-react/src/templates/workshop-template.tsx
=> feat(er): style tweaks for er v2

apps/total-typescript/src/components/articles/article-toc.tsx, apps/total-typescript/src/components/articles/mobile-article-toc.tsx, apps/total-typescript/src/pages/[article].tsx, apps/total-typescript/src/templates/article-template.tsx
=> feat(tt): articles toc

apps/epic-react/src/templates/tutorial-template.tsx
=> feat(er): add callout for erv2

apps/epic-react/src/pages/modules/[module]/completed.tsx
=> fix ER-179: completion links order

apps/epic-react/src/components/exercise-overlay.tsx, apps/epic-react/src/pages/get-started/index.tsx
=> chore: Update MuxPlayer playbackId for get-started

apps/epic-react/src/lib/lessons.ts, apps/epic-react/src/pages/api/auth/[...nextauth].ts, apps/epic-react/src/pages/api/workshops/[module]/access.ts, apps/epic-web/src/pages/api/auth/[...nextauth].ts, apps/epic-web/src/pages/api/workshops/[module]/access.ts, packages/skill-api/src/server/default-next-auth-options.ts
adds a cookie on sign in to indicate active session across subdomains
fixes ER-184
https://www.loom.com/share/f7ce051a50214956abb3bfd553cc8d4a?sid=a16c85ff-fa62-420e-8e20-7431fe59e49e
=> feat(erv2): contributes to ER-162

packages/commerce-server/src/bulk-coupon.ts, packages/commerce-server/src/format-prices-for-product.test.ts
=> feat(commerce): update bulk discount logic

apps/epic-react/package.json, apps/epic-react/src/certificate/certificate-form.tsx, apps/epic-react/src/trpc/routers/_app.ts, apps/epic-react/src/trpc/routers/certificate.ts, apps/epic-react/src/utils/cloudinary.ts, pnpm-lock.yaml
=> feat(er): enable cert uploads to cloudinary and obtain shareable url

apps/epic-react/src/pages/api/workshops/[module]/index.ts, apps/epic-web/src/pages/api/tutorials/[module]/index.ts, apps/epic-web/src/pages/api/workshops/[module]/index.ts, packages/skill-lesson/lib/modules.ts
=> feat(kcd): resources in workshops/modules api response

apps/epic-react/src/components/landing-copy.mdx
=> fix(ER): Update to correct amount of time

apps/epic-react/src/components/landing-copy-v2.mdx, apps/epic-react/src/components/landing/codebase-transformation.tsx, apps/epic-react/src/components/landing/intro-tour-video.tsx, apps/epic-react/src/components/landing/modules-list.tsx, apps/epic-react/src/components/landing/react-19-features-stack.tsx, apps/epic-react/src/pages/index.tsx, apps/epic-react/tailwind.config.js
=> feat(er2): update landing copy structure

apps/epic-react/src/lib/bonuses.ts, apps/epic-react/src/lib/products.ts, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/bonuses/[module]/[lesson]/index.tsx, apps/epic-react/src/pages/bonuses/[module]/index.tsx, apps/epic-react/src/pages/bonuses/index.tsx, apps/epic-react/src/templates/bonus-template.tsx, packages/commerce-server/src/@types/index.ts, packages/skill-lesson/video/video-overlays.tsx
=> feat(er2): bonus module routes

apps/epic-react/src/pages/_app.tsx
=> feat(er2): golden ticket share card

apps/epic-react/src/styles/video/lesson-title.css
https://github.com/user-attachments/assets/3c9e4729-f64e-430a-b668-4a8965760204
=> fix(er): light mode interview pill

apps/epic-react/src/lib/products.ts, packages/skill-lesson/path-to-purchase/pricing.tsx, packages/skill-lesson/path-to-purchase/product-tiers.tsx
If the purchased tier is higher the lower tiers are disabled 
https://github.com/user-attachments/assets/7ee161ba-e777-47f0-abc6-85a051e5d092
=> feat: when a higher tier is purchased lower can't be bought

apps/epic-react/src/lib/bonuses.ts, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/workshops/index.tsx
=> feat(erd): display progress on workshops index

apps/epic-react/src/certificate/certificate-form.tsx, apps/epic-react/src/certificate/module-certificate.tsx, apps/epic-react/src/lib/tutorials.ts, apps/epic-react/src/lib/workshops.ts, apps/epic-react/src/pages/workshops/[module]/index.tsx, apps/epic-react/src/templates/module-template.tsx, apps/epic-react/src/templates/tutorial-template.tsx
=> fix(erd): first workshop lesson link

packages/skill-api/src/core/services/process-refund.ts, packages/skill-api/src/core/services/update-name.ts
=> fix: add protection for updateName and refunds

apps/epic-web/src/components/conf/buy-tickets-cta.tsx, apps/epic-web/src/pages/conf/2024/[speaker].tsx, apps/epic-web/src/pages/conf/2024/index.tsx, apps/epic-web/src/pages/conf/2025/index.tsx
=> feat(ewd): initial epic web conf 2025 landing page

apps/epic-web/src/components/testing-landing-copy.mdx, apps/epic-web/src/pages/buy.tsx, apps/epic-web/src/pages/index.tsx, apps/epic-web/src/pages/testing/index.tsx, apps/epic-web/src/styles/commerce.css
=> style(ewd): testing bundle landing page

apps/epic-web/schemas/documents/exercise.tsx, apps/epic-web/schemas/documents/explainer.tsx, apps/epic-web/schemas/documents/lesson.tsx, apps/epic-web/schemas/objects/resources/solution.ts, packages/skill-lesson/lib/lesson-resource.ts, packages/skill-lesson/schemas/lesson.ts, packages/skill-lesson/utils/ability.ts
=> feat(ewd): control resource visibility state

apps/epic-web/src/components/exercise-overlay.tsx, apps/epic-web/src/lib/tutorials.ts, apps/epic-web/src/pages/get-started/index.tsx, apps/epic-web/src/pages/tutorials/[module]/[section]/[lesson]/index.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/index.tsx, apps/epic-web/src/pages/workshops/[module]/[section]/[lesson]/solution/index.tsx, apps/epic-web/src/templates/exercise-template.tsx, apps/epic-web/src/templates/tutorial-template.tsx, apps/epic-web/src/trpc/routers/module-resources.ts
=> feat(ewd): tutorials use workshop app too

apps/epic-web/src/styles/commerce.css, apps/epic-web/src/styles/video/video-overlays.css, packages/skill-lesson/video/video-overlays.tsx
=> feat(ewd): prioritize bundle in blocked overlay

apps/epic-web/src/lib/workshops.ts, apps/epic-web/src/pages/workshops/index.tsx, apps/epic-web/src/trpc/routers/search.ts
=> feat(ewd): search workshops and filter by contributor

apps/epic-web/src/pages/tutorials/index.tsx, apps/epic-web/src/pages/workshops/index.tsx, apps/epic-web/src/templates/tutorial-template.tsx
=> feat(ewd): tutorials search

apps/epic-web/src/components/app/layout.tsx, apps/epic-web/src/components/app/navigation.tsx, apps/epic-web/src/pages/articles.tsx, apps/epic-web/src/pages/products/index.tsx, apps/epic-web/src/styles/commerce.css
=> feat(ewd): promo banner below nav

apps/epic-web/src/inngest/functions/stripe/slack-daily-reporter.ts
=> ng/improve report and send it to us 

apps/epic-web/src/pages/conf/2025/index.tsx
=> fix: epic web conf ticket tier

packages/skill-lesson/path-to-purchase/redeem-dialog.tsx
https://github.com/user-attachments/assets/f5528c4d-7f70-488b-a4a9-b1ede480b2b2
=> fix: remove duplicate instructors in byline and make dialog scrollable

apps/epic-web/src/pages/conf/2025/index.tsx
=> feat(ew): add current sponsors

apps/epic-web/src/components/app/footer.tsx, apps/epic-web/src/pages/principles/[...principles].tsx, apps/epic-web/src/pages/principles/index.tsx, apps/epic-web/src/templates/principles-layout.tsx, apps/epic-web/tailwind.config.js
made it nicer and added mobile toc
=> style(ewd): principles

apps/epic-web/src/pages/principles/index.tsx
=> fix(ewd): epic programming (not web) principles

apps/epic-web/src/components/primary-newsletter-cta.tsx, apps/epic-web/src/pages/principles/cheatsheet.tsx, apps/epic-web/src/pages/principles/index.tsx
https://res.cloudinary.com/epic-web/image/upload/v1733383987/programming-principles-cheatsheet.pdf
=> feat(ewd): principles cheat sheet

apps/epic-web/src/principles/data.json
=> fix(ewd): principle-ize the AI principle

apps/total-typescript/src/exercise/local-dev-prefs/form.tsx
=> fix(tt): custom editor setting not visible

apps/epic-react/src/app/oauth/.well-known/openid-configuration/route.ts, apps/epic-web/src/app/oauth/.well-known/openid-configuration/route.ts
@kentcdodds this should do the trick
=> fix(kcd): openid client is more strict now

apps/epic-web/src/pages/conf/2025/index.tsx
=> fix(ew): update link to hotel for the conf

apps/epic-web/src/pages/conf/2025/boss.tsx
=> update epic web conf boss page

apps/epic-web/src/pages/conf/2025/index.tsx, apps/epic-web/src/pages/conf/2025/schedule.tsx
=> feat(ewd): add conference schedule page

apps/epic-web/src/pages/conf/2025/index.tsx
=> /conf 2025 updates

apps/total-typescript/src/pages/typescript-learning-path.tsx
TypeScritp setup --> TypeScript setup
=> Learning Path typo

apps/epic-web/.gitignore, apps/epic-web/package.json, apps/epic-web/src/components/share.tsx, apps/epic-web/src/lib/articles.ts, pnpm-lock.yaml
This merges in articles from the kcd course builder database. 
I've made sure that they are sorted in proper chronological order. 
I also went ahead and added the new env to Vercel.
=> feat: Bring in articles from epic web course builder

apps/epic-web/src/components/testing-landing-copy.mdx, apps/epic-web/src/pages/testing/boss-letter.mdx, apps/epic-web/src/pages/testing/boss.tsx
=> feat(ew): boss testing page

packages/skill-api/src/core/services/process-refund.ts
=> fix(refunds): update naming from merchantChargeId to stripeChargeId

apps/epic-web/src/pages/testing/index.tsx
=> fix(testing):  for coupon management in testing page
